[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tasha"
version = "0.4.0"
dependencies = [
    "dice",
    "prompt-toolkit",
    "toml",
]
requires-python = ">=3.8"
authors = [
    {name = "Marcus T Taylor", email="mtaylor9754@hotmail.com"},
]
maintainers = [
    {name = "Marcus T Taylor", email="mtaylor9754@hotmail.com"},
]
description = "A program to create 5th edition Dungeons & Dragons characters."
readme = "README.md"
license = "GPL-3.0-only"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: Games/Entertainment :: Role-Playing",
    "Topic :: Utilities",
]

[project.urls]
Repository = "https://github.com/mtttech/Tasha.git"
