multiclasses = {
    "multiclasses": {
        "Barbarian": {
            "ability": [
                "Strength",
            ],
            "armors": ["Shield"],
            "features": ["Rage", "Unarmored Defense", "Weapon Mastery"],
            "tools": [],
            "skills": [],
            "weapons": ["Martial"],
        },
        "Bard": {
            "ability": [
                "Charisma",
            ],
            "armors": ["Light"],
            "features": ["Bardic Inspiration", "Spellcasting"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Arcana",
                "Athletics",
                "Deception",
                "History",
                "Insight",
                "Intimidation",
                "Investigation",
                "Medicine",
                "Nature",
                "Perception",
                "Performance",
                "Persuasion",
                "Religion",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],  # Choose 1 skill
            "tools": [
                "Musical Instrument - Bagpipes",
                "Musical Instrument - Birdpipes",
                "Musical Instrument - Drum",
                "Musical Instrument - Dulcimer",
                "Musical Instrument - Flute",
                "Musical Instrument - Glaur",
                "Musical Instrument - Hand Drum",
                "Musical Instrument - Longhorn",
                "Musical Instrument - Lute",
                "Musical Instrument - Lyre",
                "Musical Instrument - Horn",
                "Musical Instrument - Pan flute",
                "Musical Instrument - Shawm",
                "Musical Instrument - Songhorn",
                "Musical Instrument - Tantan",
                "Musical Instrument - Thelarr",
                "Musical Instrument - Tocken",
                "Musical Instrument - Viol",
                "Musical Instrument - Wargong",
                "Musical Instrument - Yarting",
                "Musical Instrument - Zulkoon",
            ],  # 1 musical instrument
            "weapons": [],
        },
        "Cleric": {
            "ability": [
                "Wisdom",
            ],
            "armors": ["Light", "Medium", "Shield"],
            "features": ["Divine Order", "Spellcasting"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Druid": {
            "ability": [
                "Wisdom",
            ],
            "armors": ["Light", "Shield"],
            "features": ["Druidic", "Primal Order", "Spellcasting"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Fighter": {
            "ability": ["Dexterity", "Strength"],  # either or
            "armors": ["Light", "Medium", "Shield"],
            "features": ["Fighting Style", "Second Wind", "Weapon Mastery"],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        "Monk": {
            "ability": ["Dexterity", "Wisdom"],
            "armors": [],
            "features": ["Martial Arts", "Unarmored Defense"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Paladin": {
            "ability": ["Strength", "Charisma"],
            "armors": ["Light", "Medium", "Shield"],
            "features": ["Lay on Hands", "Spellcasting", "Weapon Mastery"],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        "Ranger": {
            "ability": [
                "Dexterity",
                "Wisdom",
            ],
            "armors": ["Light", "Medium", "Shield"],
            "features": ["Favored Enemy", "Spellcasting", "Weapon Mastery"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Insight",
                "Investigation",
                "Nature",
                "Perception",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],  # Choose 1 skill
            "tools": [],
            "weapons": ["Martial"],
        },
        "Rogue": {
            "ability": [
                "Dexterity",
            ],
            "armors": ["Light"],
            "features": [
                "Expertise",
                "Sneak Attack",
                "Thieves' Cant",
                "Weapon Mastery",
            ],
            "skills": [
                "Acrobatics",
                "Athletics",
                "Deception",
                "Insight",
                "Intimidation",
                "Investigation",
                "Perception",
                "Performance",
                "Persuasion",
                "Sleight of Hand",
                "Stealth",
            ],  # Choose 4 skills
            "tools": ["Thieves' Tools"],
            "weapons": ["Simple"],  # Martial weapons with Finesse or Light properties
        },
        "Sorcerer": {
            "ability": [
                "Charisma",
            ],
            "armors": [],
            "features": ["Innate Sorcery", "Spellcasting"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Warlock": {
            "ability": [
                "Charisma",
            ],
            "armors": ["Light"],
            "features": ["Eldritch Invocations", "Pact Magic"],
            "skills": [],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Wizard": {
            "ability": [
                "Intelligence",
            ],
            "armors": [],
            "features": ["Arcane Recovery", "Ritual Adept", "Spellcasting"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
    },
}
