proficiencies = {
    "proficiencies": {
        "armors": [
            "Heavy",
            "Light",
            "Medium",
            "Shield",
        ],
        "tools": [
            "Artisan's Tools - Alchemists Supplies",
            "Artisan's Tools - Brewer's Supplies",
            "Artisan's Tools - Calligrapher's Supplies",
            "Artisan's Tools - Carpenter's Tools",
            "Artisan's Tools - Cartographer's Tools",
            "Artisan's Tools - Cobbler's Tools",
            "Artisan's Tools - Cook's utensils",
            "Artisan's Tools - Glassblower's Tools",
            "Artisan's Tools - Jeweler's Tools",
            "Artisan's Tools - Leatherworker's Tools",
            "Artisan's Tools - Mason's Tools",
            "Artisan's Tools - Painter's Supplies",
            "Artisan's Tools - Potter's Tools",
            "Artisan's Tools - Smith's Tools",
            "Artisan's Tools - Tinker's Tools",
            "Artisan's Tools - Weaver's Tools",
            "Artisan's Tools - Woodcarver's Tools",
            "Disguise kit",
            "Forgery kit",
            "Gaming Set - Dice Set",
            "Gaming Set - Dragonchess Set",
            "Gaming Set - Playing card Set",
            "Gaming Set - Three-Dragon Ante Set",
            "Herbalism kit",
            "Musical Instrument - Bagpipes",
            "Musical Instrument - Birdpipes",
            "Musical Instrument - Drum",
            "Musical Instrument - Dulcimer",
            "Musical Instrument - Flute",
            "Musical Instrument - Glaur",
            "Musical Instrument - Hand Drum",
            "Musical Instrument - Longhorn",
            "Musical Instrument - Lute",
            "Musical Instrument - Lyre",
            "Musical Instrument - Horn",
            "Musical Instrument - Pan flute",
            "Musical Instrument - Shawm",
            "Musical Instrument - Songhorn",
            "Musical Instrument - Tantan",
            "Musical Instrument - Thelarr",
            "Musical Instrument - Tocken",
            "Musical Instrument - Viol",
            "Musical Instrument - Wargong",
            "Musical Instrument - Yarting",
            "Musical Instrument - Zulkoon",
            "Navigator's Tools",
            "Poisoner's kit",
            "Thieves' Tools",
            "Vehicle",
        ],
        "weapons": {
            "Martial": {
                "Battleaxe": {"properties": []},
                "Blowgun": {"properties": []},
                "Flail": {"properties": []},
                "Glaive": {"properties": []},
                "Greataxe": {"properties": []},
                "Greatsword": {"properties": []},
                "Halberd": {"properties": []},
                "Hand Crossbow": {"properties": []},
                "Heavy Crossbow": {"properties": []},
                "Lance": {"properties": []},
                "Longbow": {"properties": []},
                "Longsword": {"properties": []},
                "Maul": {"properties": []},
                "Morningstar": {"properties": []},
                "Musket": {"properties": []},
                "Pike": {"properties": []},
                "Pistol": {"properties": []},
                "Rapier": {"properties": ["Finesse"]},
                "Scimitar": {"properties": ["Finesse", "Light"]},
                "Shortsword": {"properties": ["Finesse", "Light"]},
                "Trident": {"properties": []},
                "War Pick": {"properties": []},
                "Warhammer": {"properties": []},
                "Whip": {"properties": ["Finesse"]},
            },
            "Simple": {
                "Club": {"properties": ["Light"]},
                "Dagger": {"properties": ["Finesse", "Light"]},
                "Dart": {"properties": ["Finesse"]},
                "Greatclub": {"properties": []},
                "Handaxe": {"properties": ["Light"]},
                "Javelin": {"properties": []},
                "Light Crossbow": {"properties": []},
                "Light Hammer": {"properties": ["Light"]},
                "Mace": {"properties": []},
                "Quarterstaff": {"properties": []},
                "Shortbow": {"properties": []},
                "Sickle": {"properties": ["Light"]},
                "Sling": {"properties": []},
                "Spear": {"properties": []},
            },
        },
    },
}
