feats = {
    "feats": {
        "Actor": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Alert": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Athlete": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Bountiful Luck": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Halfling"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Charger": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Chef": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Artisan's tools - Cook's utensils"],
            "weapons": [],
        },
        "Crossbow Expert": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Crusher": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Defensive Duelist": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Dragon Fear": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Dragonborn"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Dragon Hide": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Dragonborn"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Drow High Magic": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Elf"],
            "subrace": ["Drow"],
            "tools": [],
            "weapons": [],
        },
        "Dual Wielder": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Dungeon Delver": {
            "ability": None,
            "armors": [],
            "caster": False,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Durable": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Dwarven Fortitude": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Dwarf"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Eldritch Adept": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Artisan's tools - Cook's utensils"],
            "weapons": [],
        },
        "Elemental Adept": {
            "ability": None,
            "armors": [],
            "caster": True,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Elven Accuracy": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Elf", "HalfElf"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Fade Away": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Gnome"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Fey Teleportation": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Elf"],
            "subrace": ["High"],
            "tools": [],
            "weapons": [],
        },
        "Fey Touched": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Fighting Initiative": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Artisan's tools - Cook's utensils"],
            "weapons": [],
        },
        "Flames of Phlegethos": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Tiefling"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Grappler": {
            "ability": {"Strength": 13},
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Great Weapon Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Gunner": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": ["Firearms"],
        },
        "Healer": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Heavily Armored": {
            "ability": None,
            "armors": [
                "Heavy",
            ],
            "caster": None,
            "proficiency": {"armors": ["Medium"]},
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Heavy Armor Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": {"armors": ["Heavy"]},
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Infernal Constitution": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Tiefling"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Inspiring Leader": {
            "ability": {"Charisma": 13},
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Keen Mind": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Lightly Armored": {
            "ability": None,
            "armors": [
                "Light",
            ],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Linguist": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Lucky": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Mage Slayer": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Magic Initiate": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Martial Adept": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Medium Armor Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": {"armors": ["Medium"]},
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Metamagic Adept": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Artisan's tools - Cook's utensils"],
            "weapons": [],
        },
        "Mobile": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Moderately Armored": {
            "ability": None,
            "armors": ["Medium", "Shield"],
            "caster": None,
            "proficiency": {"armors": ["Light"]},
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Mounted Combatant": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Observant": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Orcish Fury": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["HalfOrc"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Piercer": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Poisoner": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Poisoner's kit"],
            "weapons": [],
        },
        "Polearm Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Prodigy": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["HalfElf", "HalfOrc", "Human"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Resilient": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Ritual Caster": {
            "ability": {"Intelligence": 13, "Wisdom": 13},
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Savage Attacker": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Second Chance": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Halfling"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Sentinel": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Shadow Touched": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": ["Artisan's tools - Cook's utensils"],
            "weapons": [],
        },
        "Sharpshooter": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Shield Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Skill Expert": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Skilled": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Skulker": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Slasher": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Spell Sniper": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Squat Nimbleness": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Dwarf", "Gnome", "Halfling"],
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Svirfneblin Magic": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Gnome"],
            "subrace": ["Deep"],
            "tools": [],
            "weapons": [],
        },
        "Tavern Brawler": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [
                "Improvised weapons",
                "Unarmed strikes",
            ],
        },
        "Telekinetic": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Telepathic": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Tough": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "War Caster": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Weapon Master": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": None,
            "subrace": None,
            "tools": [],
            "weapons": [],
        },
        "Wood Elf Magic": {
            "ability": None,
            "armors": [],
            "caster": None,
            "proficiency": None,
            "race": ["Elf"],
            "subrace": ["Wood"],
            "tools": [],
            "weapons": [],
        },
    },
}
