proficiencies = {
    "proficiencies": {
        "armors": [
            "Heavy",
            "Light",
            "Medium",
            "Shield",
        ],
        "tools": [
            "Artisan's tools - Alchemists supplies",
            "Artisan's tools - Brewer's supplies",
            "Artisan's tools - Calligrapher's supplies",
            "Artisan's tools - Carpenter's tools",
            "Artisan's tools - Cartographer's tools",
            "Artisan's tools - Cobbler's tools",
            "Artisan's tools - Cook's utensils",
            "Artisan's tools - Glassblower's tools",
            "Artisan's tools - Jeweler's tools",
            "Artisan's tools - Leatherworker's tools",
            "Artisan's tools - Mason's tools",
            "Artisan's tools - Painter's supplies",
            "Artisan's tools - Potter's tools",
            "Artisan's tools - Smith's tools",
            "Artisan's tools - Tinker's tools",
            "Artisan's tools - Weaver's tools",
            "Artisan's tools - Woodcarver's tools",
            "Disguise kit",
            "Forgery kit",
            "Gaming set - Dice set",
            "Gaming set - Dragonchess set",
            "Gaming set - Playing card set",
            "Gaming set - Three-Dragon Ante set",
            "Herbalism kit",
            "Musical instrument - Bagpipes",
            "Musical instrument - Birdpipes",
            "Musical instrument - Drum",
            "Musical instrument - Dulcimer",
            "Musical instrument - Flute",
            "Musical instrument - Glaur",
            "Musical instrument - Hand Drum",
            "Musical instrument - Longhorn",
            "Musical instrument - Lute",
            "Musical instrument - Lyre",
            "Musical instrument - Horn",
            "Musical instrument - Pan flute",
            "Musical instrument - Shawm",
            "Musical instrument - Songhorn",
            "Musical instrument - Tantan",
            "Musical instrument - Thelarr",
            "Musical instrument - Tocken",
            "Musical instrument - Viol",
            "Musical instrument - Wargong",
            "Musical instrument - Yarting",
            "Musical instrument - Zulkoon",
            "Navigator's tools",
            "Poisoner's kit",
            "Thieves' tools",
            "Vehicle",
        ],
        "weapons": {
            "Martial": [
                "Battleaxe",
                "Blowgun",
                "Flail",
                "Greataxe",
                "Greatsword",
                "Halberd",
                "Hand Crossbow",
                "Heavy Crossbow",
                "Lance",
                "Longbow",
                "Longsword",
                "Maul",
                "Morningstar",
                "Net",
                "Pike",
                "Rapier",
                "Scimitar",
                "Shortsword",
                "Trident",
                "War pick",
                "Warhammer",
                "Whip",
            ],
            "Simple": [
                "Club",
                "Dagger",
                "Dart",
                "Greatclub",
                "Handaxe",
                "Javelin",
                "Light Crossbow",
                "Light hammer",
                "Mace",
                "Quarterstaff",
                "Shortbow",
                "Sickle",
                "Sling",
                "Spear",
                "Unarmed strike",
            ],
        },
    },
}
