races = {
    "races": {
        # VGtM pg 104
        "Aasimar": {
            "armors": [],
            "bonus": {"Charisma": 2},
            "languages": ["Common", "Celestial"],
            "resistances": ["Necrotic", "Radiant"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": ["Fallen", "Protector", "Scourge"],
            "tools": [],
            "traits": ["Celestial Legacy", "Celestial Resistance", "Darkvision"],
            "weapons": [],
        },
        "Bugbear": {
            "armors": [],
            "bonus": {"Dexterity": 1, "Strength": 2},
            "languages": ["Common", "Goblin"],
            "resistances": [],
            "size": "Medium",
            "skills": ["Stealth"],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Darkvision",
                "Long-Limbed",
                "Powerful Build",
                "Sneaky",
                "Surprise Attack",
            ],
            "weapons": [],
        },
        "Dragonborn": {
            "armors": [],
            "bonus": {"Charisma": 1, "Strength": 2},
            "languages": ["Common", "Draconic"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Breath Weapon", "Damage Resistance", "Draconic Ancestry"],
            "weapons": [],
        },
        "Dwarf": {
            "armors": [],
            "bonus": {"Constitution": 2},
            "languages": ["Common", "Dwarvish"],
            "resistances": ["Poison"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": ["Duergar", "Hill", "Mountain"],
            "tools": [],
            "traits": [
                "Darkvision",
                "Dwarven Combat Training",
                "Dwarven Resilience",
                "Dwarven Toughness",
                "Stonecunning",
                "Tool Proficiency",
            ],
            "weapons": ["Battleaxe", "Handaxe", "Throwing hammer", "Warhammer"],
        },
        "Elf": {
            "armors": [],
            "bonus": {"Dexterity": 2},
            "languages": ["Common", "Elvish"],
            "resistances": ["Charm", "Sleep"],
            "size": "Medium",
            "skills": ["Perception"],
            "spells": [],
            "subrace": ["Drow", "Eladrin", "High", "Sea", "Shadar-kai", "Wood"],
            "tools": [],
            "traits": ["Darkvision", "Fey Ancestry", "Keen Senses", "Trance"],
            "weapons": [],
        },
        "Fairy": {
            "armors": [],
            "bonus": {},
            "languages": [
                "Common",
            ],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": {1: ["Druidcraft"], 3: ["Faerie Fire"], 5: ["Enlarge/Reduce"]},
            "subrace": [],
            "tools": [],
            "traits": [
                "Fairy Magic",
                "Flight",
            ],
            "weapons": [],
        },
        # VGtM pg 106
        "Firbolg": {
            "armors": [],
            "bonus": {"Strength": 1, "Wisdom": 2},
            "languages": ["Common", "Elvish", "Giant"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Firbolg Magic",
                "Hidden Step",
                "Powerful Build",
                "Speech of Beast and Leaf",
            ],
            "weapons": [],
        },
        "Gith": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": ["Common", "Gith"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": ["Githyanki", "Githzerai"],
            "tools": [],
            "traits": [],
            "weapons": [],
        },
        "Gnome": {
            "armors": [],
            "bonus": {"Intelligence": 2},
            "languages": ["Common", "Gnomish"],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "subrace": ["Deep", "Forest", "Rock"],
            "tools": [],
            "traits": ["Gnome Cunning", "Darkvision"],
            "weapons": [],
        },
        "Goblin": {
            "armors": [],
            "bonus": {"Constitution": 1, "Dexterity": 2},
            "languages": ["Common", "Goblin"],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Darkvision", "Fury of the Small", "Nimble Escape"],
            "weapons": [],
        },
        # VGtM pg 108
        "Goliath": {
            "armors": [],
            "bonus": {"Constitution": 1, "Strength": 2},
            "languages": ["Common", "Giant"],
            "resistances": [],
            "size": "Medium",
            "skills": ["Athletics"],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Natural Athlete",
                "Stone's Endurance",
                "Powerful Build",
                "Mountain Born",
            ],
            "weapons": [],
        },
        "Halfelf": {
            "armors": [],
            "bonus": {"Charisma": 2},
            "languages": ["Common", "Elvish"],
            "resistances": ["Charm", "Sleep"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Darkvision", "Fey Ancestry", "Languages", "Skill Versatility"],
            "weapons": [],
        },
        "Halforc": {
            "armors": [],
            "bonus": {"Constitution": 1, "Strength": 2},
            "languages": ["Common", "Orc"],
            "resistances": [],
            "size": "Medium",
            "skills": ["Intimidation"],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Darkvision",
                "Menacing",
                "Relentless Endurance",
                "Savage Attacks",
            ],
            "weapons": [],
        },
        "Halfling": {
            "armors": [],
            "bonus": {"Dexterity": 2},
            "languages": ["Common", "Halfling"],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "subrace": ["Lightfoot", "Stout"],
            "tools": [],
            "traits": ["Brave", "Halfling Nimbleness", "Lucky"],
            "weapons": [],
        },
        "Harengon": {
            "armors": [],
            "bonus": {},
            "languages": [
                "Common",
            ],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Hare Trigger",
                "Lucky Footwork",
                "Rabbit Hop",
            ],
            "weapons": [],
        },
        "Hobgoblin": {
            "armors": [],
            "bonus": {"Constitution": 2, "Intelligence": 1},
            "languages": ["Common", "Goblin"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Darkvision", "Martial Training", "Saving Face"],
            "weapons": [],
        },
        "Human": {
            "armors": [],
            "bonus": {
                "Charisma": 1,
                "Constitution": 1,
                "Dexterity": 1,
                "Intelligence": 1,
                "Strength": 1,
                "Wisdom": 1,
            },
            "languages": ["Common"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Languages"],
            "weapons": [],
        },
        # VGtM pg 109
        "Kenku": {
            "armors": [],
            "bonus": {"Dexterity": 2, "Wisdom": 1},
            "languages": ["Common", "Auran"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Expert Forgery", "Kenku Training", "Mimicry"],
            "weapons": [],
        },
        "Kobold": {
            "armors": [],
            "bonus": {"Dexterity": 2, "Strength": -2},
            "languages": ["Common", "Draconic"],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Darkvision",
                "Grovel, Cower, and Beg",
                "Pack Tactics",
                "Sunlight Sensitivity",
            ],
            "weapons": [],
        },
        # VGtM pg 111
        "Lizardfolk": {
            "armors": [],
            "bonus": {"Constitution": 2, "Wisdom": 1},
            "languages": ["Common", "Draconic"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Bite",
                "Cunning Artisan",
                "Hold Breath",
                "Hunter's Lore",
                "Natural Armor",
                "Hungry Jaws",
            ],
            "weapons": [],
        },
        "Orc": {
            "armors": [],
            "bonus": {"Constitution": 1, "Strength": 2},
            "languages": ["Common", "Orc"],
            "resistances": [],
            "size": "Medium",
            "skills": ["Intimidation"],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": ["Darkvision", "Aggressive", "Menacing", "Powerful Build"],
            "weapons": [],
        },
        # VGtM pg 113
        "Tabaxi": {
            "armors": [],
            "bonus": {"Charisma": 1, "Dexterity": 2},
            "languages": ["Common"],
            "resistances": [],
            "size": "Medium",
            "skills": ["Perception"],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Darkvision",
                "Feline Agility",
                "Cat's Claws",
                "Cat's Talent",
                "Languages",
            ],
            "weapons": [],
        },
        "Tiefling": {
            "armors": [],
            "bonus": {"Charisma": 2},
            "languages": ["Common", "Infernal"],
            "resistances": ["Fire"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [
                "Asmodeus",
                "Baalzebul",
                "Dispater",
                "Fierna",
                "Glasya",
                "Levistus",
                "Mammon",
                "Mephistopheles",
                "Zariel",
            ],
            "tools": [],
            "traits": ["Darkvision", "Hellish Resistance"],
            "weapons": [],
        },
        # VGtM pg 115
        "Triton": {
            "armors": [],
            "bonus": {"Charisma": 1, "Constitution": 1, "Strength": 1},
            "languages": ["Common", "Primordial"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "subrace": [],
            "tools": [],
            "traits": [
                "Amphibious",
                "Control Air and Water",
                "Emissary of the Sea",
                "Guardians of the Depths",
            ],
            "weapons": [],
        },
        "Yuanti": {
            "armors": [],
            "bonus": {"Charisma": 2, "Intelligence": 1},
            "languages": ["Abyssal", "Common", "Draconic"],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": {1: ["Animal Friendship", "Poison Spray"], 3: ["Suggestion"]},
            "subrace": [],
            "tools": [],
            "traits": [
                "Darkvision",
                "Innate Spellcasting",
                "Magic Resistance",
                "Poison Immunity",
            ],
            "weapons": [],
        },
    },
}
