subclasses = {
    "subclasses": {
        "Aberrant Mind": {
            "armors": [],
            "features": {
                1: ["Psionic Spells", "Telepathic Speech"],
                6: ["Psionic Sorcery", "Psychic Defenses"],
                14: ["Revelation in Flesh"],
                18: ["Warping Implosion"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Alchemist": {
            "armors": [],
            "features": {
                3: ["Tool Proficiency", "Alchemist Spells", "Experimental Elixir"],
                5: ["Alchemical Savant"],
                9: ["Restorative Reagents"],
                15: ["Chemical Mastery"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Artisan's tools - Alchemists supplies"],
            "weapons": [],
        },
        "Arcana Domain": {
            "armors": [],
            "features": {
                1: ["Arcane Initiate"],
                2: ["Channel Divinity - Arcane Abjuration"],
                6: ["Spell Breaker"],
                8: ["Potent Spellcasting"],
                17: ["Arcane Mastery"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 28
        "Arcane Archer": {
            "armors": [],
            "features": {
                3: ["Arcane Archer Lore", "Arcane Shot (2 options)"],
                7: ["Curving Shot", "Magic Arrow", "Arcane Shot (3 options)"],
                10: ["Arcane Shot (4 options)"],
                15: ["Ever-Ready Shot", "Arcane Shot (5 options)"],
                18: ["Arcane Shot (6 options, improved shots)"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Arcane Trickster": {
            "armors": [],
            "features": {
                3: ["Mage Hand Legerdemain", "Spellcasting"],
                9: ["Magical Ambush"],
                13: ["Versatile Trickster"],
                17: ["Spell Thief"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Armorer": {
            "armors": ["Heavy"],
            "features": {
                3: [
                    "Tools of the Trade",
                    "Armorer Spells",
                    "Arcane Armor",
                    "Armor Model",
                ],
                5: ["Extra Attack"],
                9: ["Armor Modifications"],
                15: ["Perfected Armor"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Artisan's tools - Smith's tools"],
            "weapons": [],
        },
        "Artillerist": {
            "armors": [],
            "features": {
                3: ["Tool Proficiency", "Artillerist Spells", "Eldritch Cannon"],
                5: ["Arcane Firearm"],
                9: ["Explosive Cannon"],
                15: ["Fortified Position"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Artisan's tools - Woodcarver's tools"],
            "weapons": [],
        },
        "Assassin": {
            "armors": [],
            "features": {
                3: ["Assassinate"],
                9: ["Infiltration Expertise"],
                13: ["Impostor"],
                17: ["Death Strike"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Disguise kit", "Poisoner's kit"],
            "weapons": [],
        },
        "Banneret": {
            "armors": [],
            "features": {
                3: ["Rallying Cry"],
                7: ["Royal Envoy"],
                10: ["Inspiring Surge"],
                15: ["Bulwark"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Battle Master": {
            "armors": [],
            "features": {
                3: ["Combat Superiority", "Student of War"],
                7: ["Know Your Enemy"],
                10: ["Improved Combat Superiority"],
                15: ["Relentless"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Battle Smith": {
            "armors": [],
            "features": {
                3: [
                    "Tool Proficiency",
                    "Battle Smith Spells",
                    "Battle Ready",
                    "Steel Defender",
                ],
                5: ["Extra Attack"],
                9: ["Arcane Jolt"],
                15: ["Improved Defender"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Artisan's tools - Smith's tools"],
            "weapons": ["Martial"],
        },
        "Beast Master": {
            "armors": [],
            "features": {
                3: ["Ranger's Companion"],
                7: ["Exceptional Training"],
                11: ["Beastial Fury"],
                15: ["Share Spells"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Bladesinging": {
            "armors": ["Light"],
            "features": {
                2: ["Bladesong"],
                6: ["Extra Attack"],
                10: ["Song of Defense"],
                14: ["Song of Victory"],
            },
            "languages": [],
            "skills": ["Performance"],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 30
        "Cavalier": {
            "armors": [],
            "features": {
                3: ["Bonus Proficiency", "Born to the Saddle", "Unwavering Mark"],
                7: ["Warding Maneuver"],
                10: ["Hold the Line"],
                15: ["Ferocious Charger"],
                18: ["Vigilant Defender"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Champion": {
            "armors": [],
            "features": {
                3: ["Improved Critical"],
                7: ["Remarkable Athlete"],
                10: ["Additional Fighting Style"],
                15: ["Superior Critical"],
                18: ["Survivor"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 22
        "Circle of Dreams": {
            "armors": [],
            "features": {
                2: ["Balm of the Summer Court"],
                6: ["Hearth of Moonlight and Shadow"],
                10: ["Hidden Paths"],
                14: ["Walker in Dreams"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of Spores": {
            "armors": [],
            "features": {
                2: ["Circle Spells", "Halo of Spores", "Symbiotic Entity"],
                6: ["Fungal Infestation"],
                10: ["Spreading Spores"],
                14: ["Fungal Body"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of Stars": {
            "armors": [],
            "features": {
                2: ["Star Map", "Starry Form"],
                6: ["Cosmic Omen"],
                10: ["Twinkling Constellations"],
                14: ["Full of Stars"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of Wildfire": {
            "armors": [],
            "features": {
                2: ["Circle Spells", "Summon Wildfire Spirit"],
                6: ["Enhance Bond"],
                10: ["Cauterizing Flames"],
                14: ["Blazing Revival"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Arctic": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Coast": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Desert": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Forest": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Grassland": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Moon": {
            "armors": [],
            "features": {
                2: ["Circle Forms", "Combat Wild Shape"],
                6: ["Primal Strike"],
                10: ["Elemental Wild Shape"],
                14: ["Thousand Forms"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Mountain": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 23
        "Circle of the Shepherd": {
            "armors": [],
            "features": {
                2: ["Speech of the Woods", "Spirit Totem"],
                6: ["Mighty Summoner"],
                10: ["Guardian Spirit"],
                14: ["Faithful Summons"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Swamp": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Circle of the Underdark": {
            "armors": [],
            "features": {
                2: ["Bonus Cantrip", "Natural Recovery"],
                6: ["Land's Stride"],
                10: ["Nature's Ward"],
                14: ["Nature's Sanctuary"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Clockwork Soul": {
            "armors": [],
            "features": {
                1: ["Clockwork Magic", "Restore Balance"],
                6: ["Bastion of Law"],
                14: ["Trance of Order"],
                18: ["Clockwork Cavalcade"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "College of Creation": {
            "armors": [],
            "features": {
                3: ["Mote of Potential", "Performance of Creation"],
                6: ["Animating Performance"],
                14: ["Creative Crescendo"],
                14: ["Vengeful Ancestors", "Spirit Shield (4d6)"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "College of Eloquence": {
            "armors": [],
            "features": {
                3: ["Silver Tongue", "Unsettling Words"],
                6: ["Unfailing Inspiration", "Universal Speech"],
                14: ["Infectious Inspiration"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 14
        "College of Glamour": {
            "armors": [],
            "features": {
                3: ["Enthralling Performance", "Mantle of Inspiration"],
                6: ["Mantle of Majesty"],
                14: ["Unbreakable Majesty"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "College of Lore": {
            "armors": [],
            "features": {
                3: ["Cutting Words"],
                6: ["Additional Magical Secrets"],
                14: ["Peerless Skill"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 15
        "College of Swords": {
            "armors": ["Medium"],
            "features": {
                3: ["Blade Flourish", "Bonus Proficiencies", "Fighting Style"],
                6: ["Extra Attack"],
                14: ["Master's Flourish"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": ["Scimitar"],
        },
        "College of Valor": {
            "armors": ["Medium", "Shield"],
            "features": {
                3: ["Combat Inspiration"],
                6: ["Extra Attack"],
                14: ["Battle Magic"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        # XGtE pg 16
        "College of Whispers": {
            "armors": [],
            "features": {
                3: ["Psychic Blades", "Words of Terror"],
                6: ["Mantle of Whispers"],
                14: ["Shadow Lore"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Death Domain": {
            "armors": [],
            "features": {
                1: ["Reaper"],
                2: ["Channel Divinity - Touch of Death"],
                6: ["Inescapable Destruction"],
                8: ["Divine Strike"],
                17: ["Improved Reaper"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [
                "Martial",
            ],
        },
        # XGtE pg 50
        "Divine Soul": {
            "armors": [],
            "features": {
                1: ["Favored by the Gods"],
                3: ["Divine Magic", "Favored by the Gods"],
                6: ["Empowered Healing"],
                14: ["Otherworldly Wings"],
                18: ["Unearthly Recovery"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Draconic Bloodline": {
            "armors": [],
            "features": {
                1: ["Draconic Resilience", "Dragon Ancestor"],
                6: ["Elemental Affinity"],
                14: ["Dragon Wings"],
                18: ["Draconic Presence"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Eldritch Knight": {
            "armors": [],
            "features": {
                3: ["Spellcasting", "Weapon Bond"],
                7: ["War Magic"],
                10: ["Eldritch Strike"],
                15: ["Arcane Charge"],
                18: ["Improved War Magic"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Fey Wanderer": {
            "armors": [],
            "features": {
                3: [
                    "Dreadful Strikes",
                    "Fey Wanderer Magic",
                    "Otherwordly Glamour",
                ],
                7: ["Beguiling Twist"],
                11: ["Fey Reinforcements"],
                15: ["Misty Wanderer"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Forge Domain": {
            "armors": ["Heavy"],
            "features": {
                1: ["Bonus Proficiencies", "Blessing of the Forge"],
                2: ["Channel Divinity - Artisan's Blessing"],
                6: ["Soul of the Forge"],
                8: ["Divine Strike (1d8)"],
                14: ["Divine Strike (2d8)"],
                17: ["Saint of Forge and Fire"],
            },
            "languages": [],
            "skills": [],
            "tools": ["Artisan's tools - Smith's tools"],
            "weapons": [],
        },
        # XGtE pg 41
        "Gloom Stalker": {
            "armors": [],
            "features": {
                3: [
                    "Dread Ambusher",
                    "Gloom Stalker Magic",
                    "Umbral Sight",
                ],
                7: ["Iron Mind"],
                11: ["Stalker's Flurry"],
                15: ["Shadowy Dodge"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Grave Domain": {
            "armors": [],
            "features": {
                1: ["Circle of Mortality", "Eyes of the Grave"],
                2: ["Channel Divinity - Path to the Grave"],
                6: ["Sentinel at Death's Door"],
                8: ["Potent Spellcasting"],
                17: ["Keeper of Souls"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 42
        "Horizon Walker": {
            "armors": [],
            "features": {
                3: [
                    "Detect Portal",
                    "Horizon Walker Magic",
                    "Planar Warrior (1d8)",
                ],
                7: ["Etheral Step"],
                11: ["Distant Strike", "Planar Warrior (2d8)"],
                15: ["Spectral Defense"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Hunter": {
            "armors": [],
            "features": {
                3: ["Hunter's Prey"],
                7: ["Defensive Tactics"],
                11: ["Multiattack"],
                15: ["Superior Hunter's Defense"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 45
        "Inquisitive": {
            "armors": [],
            "features": {
                3: ["Ear for Deceit", "Eye for Detail", "Insightful Fighting"],
                9: ["Steady Eye"],
                13: ["Unerring Eye"],
                17: ["Eye for Weakness"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Knowledge Domain": {
            "armors": [],
            "features": {
                1: ["Blessings of Knowledge"],
                2: ["Channel Divinity - Knowledge of the Ages"],
                6: ["Channel Divinity - Read Thoughts"],
                8: ["Potent Spellcasting"],
                17: ["Visions of the Past"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Life Domain": {
            "armors": ["Heavy"],
            "features": {
                1: ["Disciple of Life"],
                3: ["Channel Divinity - Preserve Life"],
                6: ["Blessed Healer"],
                8: ["Divine Strike"],
                17: ["Supreme Healing"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Light Domain": {
            "armors": [],
            "features": {
                1: ["Bonus Cantrip", "Warding Flare"],
                2: ["Channel Divinity - Radiance of the Dawn"],
                6: ["Improved Flare"],
                8: ["Potent Spellcasting"],
                17: ["Corona of Light"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 46
        "Mastermind": {
            "armors": [],
            "features": {
                3: ["Master of Intrigue", "Master of Tactics"],
                9: ["Insightful Manipulator"],
                13: ["Misdirection"],
                17: ["Soul of Deceit"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 43
        "Monster Slayer": {
            "armors": [],
            "features": {
                3: [
                    "Hunter's Sense",
                    "Monster Slayer Magic",
                    "Slayer's Prey",
                ],
                7: ["Supernatural Defense"],
                11: ["Magic User's Nemesis"],
                15: ["Slayer's Counter"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Nature Domain": {
            "armors": ["Heavy"],
            "features": {
                1: ["Acolyte of Nature"],
                2: ["Channel Divinity - Charm Animals and Plants"],
                6: ["Dampen Elements"],
                8: ["Divine Strike"],
                17: ["Master of Nature"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oathbreaker": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Control Undead",
                    "Channel Divinity - Dreadful Aspect",
                    "Oathbreaker Spells",
                ],
                7: ["Aura of Hate"],
                15: ["Supernatural Resistance"],
                20: ["Dread Lord"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 37
        "Oath of Conquest": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Conquering Presence",
                    "Channel Divinity - Guided Strike",
                    "Oath Spells",
                ],
                7: ["Aura of Conquest"],
                15: ["Scornful Rebuke"],
                18: ["Aura of Conquest"],
                20: ["Invincible Conqueror"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of Devotion": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Sacred Weapon",
                    "Channel Divinity - Turn the Unholy",
                    "Oath Spells",
                ],
                6: ["Aura of Devotion"],
                15: ["Purity of Spirit"],
                20: ["Holy Nimbus"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of Glory": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Peerless Athlete",
                    "Channel Divinity - Inspiring Smite",
                    "Oath Spells",
                ],
                7: ["Aura of Alacrity"],
                15: ["Glorious Defense"],
                20: ["Living Legend"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 38
        "Oath of Redemption": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Emissary of Peace",
                    "Channel Divinity - Rebuke the Violent",
                    "Oath Spells",
                ],
                7: ["Aura of the Guardian (10 ft.)"],
                15: ["Protective Spirit"],
                18: ["Aura of the Guardian (30 ft.)"],
                20: ["Emissary of Redemption"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of Vengeance": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Abjure Enemy",
                    "Channel Divinity - Vow of Enmity",
                    "Oath Spells",
                ],
                7: ["Relentless Avenger"],
                15: ["Soul of Vengeance"],
                20: ["Avenging Angel"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of the Ancients": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Nature's Wrath",
                    "Channel Divinity - Turn the Faithless",
                    "Oath Spells",
                ],
                7: ["Aura of Warding"],
                15: ["Undying Sentinel"],
                20: ["Elder Champion"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of the Crown": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Champion's Challenge",
                    "Channel Divinity - Turn the Tide",
                    "Oath Spells",
                ],
                7: ["Divine Allegiance"],
                15: ["Unyielding Spirit"],
                20: ["Exalted Champion"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Oath of the Watchers": {
            "armors": [],
            "features": {
                3: [
                    "Channel Divinity - Watcher's Will",
                    "Channel Divinity - Abjure the Extraplanar",
                    "Oath Spells",
                ],
                7: ["Aura of the Sentinel"],
                15: ["Vigilant Rebuke"],
                20: ["Mortal Bulwark"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Order Domain": {
            "armors": [
                "Heavy",
            ],
            "features": {
                1: ["Voice of Authority"],
                2: ["Channel Divinity - Order's Demand"],
                6: ["Embodiment of the Law"],
                8: ["Divine Strike"],
                17: ["Order's Wrath"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Order of Scribes": {
            "armors": [],
            "features": {
                2: ["Wizardly Quill", "Awakened Spellbook"],
                6: ["Manifest Mind"],
                10: ["Master Scrivener"],
                14: ["One With the Word"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of Wild Magic": {
            "armors": [],
            "features": {
                3: ["Magic Awareness", "Wild Surge"],
                6: ["Bolstering Magic"],
                10: ["Unstable Backlash"],
                14: ["Controlled Surge"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Ancestral Guardian": {
            "armors": [],
            "features": {
                3: ["Ancestral Protectors"],
                6: ["Spirit Shield (2d6)"],
                10: ["Consult the Spirits", "Spirit Shield (3d6)"],
                14: ["Vengeful Ancestors", "Spirit Shield (4d6)"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Battlerager": {
            "armors": [],
            "features": {
                3: ["Battlerager Armor"],
                6: ["Reckless Abandon"],
                10: ["Battlerager Charge"],
                14: ["Spiked Retribution"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Beast": {
            "armors": [],
            "features": {
                3: ["Form of the Beast"],
                6: ["Beastial Soul"],
                10: ["Infectious Fury"],
                14: ["Call of the Hunt"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Berserker": {
            "armors": [],
            "features": {
                3: ["Frenzy"],
                6: ["Mindless Rage"],
                10: ["Intimidating Presence"],
                14: ["Retaliation"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Storm Herald": {
            "armors": [],
            "features": {
                3: ["Storm Aura"],
                6: ["Storm Soul"],
                10: ["Shielding Storm"],
                14: ["Raging Storm"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Totem Warrior": {
            "armors": [],
            "features": {
                3: ["Beast Sense", "Speak with Animals", "Totem Spirit"],
                6: ["Aspect of the Beast"],
                10: ["Spirit Walker"],
                14: ["Totemic Attunement"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Path of the Zealot": {
            "armors": [],
            "features": {
                3: ["Divine Fury", "Warrior of the Gods"],
                6: ["Fanatical Focus"],
                10: ["Zealous Presence"],
                14: ["Rage beyond Death"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Peace Domain": {
            "armors": [],
            "features": {
                1: ["Emboldening Bond"],
                2: ["Channel Divinity - Balm of Peace"],
                6: ["Protective Bond"],
                8: ["Potent Spellcasting"],
                17: ["Expansive Bond"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Phantom": {
            "armors": [],
            "features": {
                3: [
                    "Steady Aim",
                    "Whispers of the Dead",
                    "Wails From the Grave",
                ],
                9: ["Tokens of the Departed"],
                13: ["Ghost Walk"],
                17: ["Death's Friend"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Psi Warrior": {
            "armors": [],
            "features": {
                3: ["Psionic Power"],
                7: ["Telekinetic Adept"],
                10: ["Guarded Mind"],
                15: ["Bulwark of Force"],
                18: ["Telekinetic Master"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Rune Knight": {
            "armors": [],
            "features": {
                3: [
                    "Bonus Proficiencies",
                    "Rune Carver",
                    "Giant's Might",
                ],
                7: ["Runic Shield"],
                10: ["Great Stature"],
                15: ["Master of Runes"],
                18: ["Runic Juggernaut"],
            },
            "languages": [
                "Giant",
            ],
            "skills": [],
            "tools": [
                "Artisan's tools - Smith's tools",
            ],
            "weapons": [],
        },
        # XGtE pg 31
        "Samurai": {
            "armors": [],
            "features": {
                3: ["Bonus Proficiency", "Fighting Spirit (5 temp. hp)"],
                7: ["Elegant Courtier"],
                10: ["Tireless Spirit, Fighting Spirit (10 temp. hp)"],
                15: ["Rapid Strike", "Fighting Spirit (15 temp. hp)"],
                18: ["Strength before Death"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Abjuration": {
            "armors": [],
            "features": {
                2: ["Abjuration Savant", "Arcane Ward"],
                6: ["Projected Ward"],
                10: ["Improved Abjuration"],
                14: ["Spell Resistance"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Conjuration": {
            "armors": [],
            "features": {
                2: ["Conjuration Savant", "Minor Conjuration"],
                6: ["Benign Transposition"],
                10: ["Focused Conjuration"],
                14: ["Durable Summons"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Divination": {
            "armors": [],
            "features": {
                2: ["Divination Savant", "Portent"],
                6: ["Expert Divination"],
                10: ["The Third Eye"],
                14: ["Greater Portent"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Enchantment": {
            "armors": [],
            "features": {
                2: ["Enchantment Savant", "Hypnotic Gaze"],
                6: ["Instinctive Charm"],
                10: ["Split Enchantment"],
                14: ["Alter Memories"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Evocation": {
            "armors": [],
            "features": {
                2: ["Evocation Savant", "Sculpt Spells"],
                6: ["Potent Cantrip"],
                10: ["Empowered Evocation"],
                14: ["Overchannel"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Illusion": {
            "armors": [],
            "features": {
                2: ["Illusion Savant", "Improved Minor Illusion"],
                6: ["Malleable Illusions"],
                10: ["Illusory Self"],
                14: ["Illusory Reality"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Necromancy": {
            "armors": [],
            "features": {
                2: ["Necromancy Savant", "Grim Harvest"],
                6: ["Undead Thralls"],
                10: ["Inured to Undeath"],
                14: ["Command Undead"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "School of Transmutation": {
            "armors": [],
            "features": {
                2: ["Transmutation Savant", "Minor Alchemy"],
                6: ["Transmuter's Stone"],
                10: ["Shapechanger"],
                14: ["Master Transmuter"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 47
        "Scout": {
            "armors": [],
            "features": {
                3: ["Skirmisher", "Survivalist"],
                9: ["Superior Mobility"],
                13: ["Ambush Master"],
                17: ["Sudden Strike"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 50
        "Shadow Magic": {
            "armors": [],
            "features": {
                1: ["Eyes of the Dark (darkvision)", "Strength of the Grave"],
                3: ["Eyes of the Dark (darkness)"],
                6: ["Hound of Ill Omen"],
                14: ["Shadow Walk"],
                18: ["Umbral Form"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Soulknife": {
            "armors": [],
            "features": {
                3: [
                    "Psionic Power",
                    "Psychic Blades",
                ],
                9: ["Soul Blades"],
                13: ["Psychic Veil"],
                17: ["Rend Mind"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 51
        "Storm Sorcery": {
            "armors": [],
            "features": {
                1: ["Wind Speaker", "Tempestuous Magic"],
                6: ["Heart of the Storm", "Storm Guide"],
                14: ["Storm's Fury"],
                18: ["Wind Soul"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Swarmkeeper": {
            "armors": [],
            "features": {
                3: [
                    "Gathered Swarm",
                    "Swarmkeeper Magic",
                ],
                7: ["Writhing Tide"],
                11: ["Mighty Swarm"],
                15: ["Swarming Dispersal"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 47
        "Swashbuckler": {
            "armors": [],
            "features": {
                3: ["Fancy Footwork", "Rakish Audacity"],
                9: ["Panache"],
                13: ["Elegant Maneuver"],
                17: ["Master Duelist"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Tempest Domain": {
            "armors": ["Heavy"],
            "features": {
                1: ["Wrath of the Storm"],
                2: ["Channel Divinity - Destructive Wrath"],
                6: ["Thunderbolt Strike"],
                8: ["Divine Strike"],
                17: ["Stormborn"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        "The Archfey": {
            "armors": [],
            "features": {
                1: ["Expanded Spell List", "Fey Presence"],
                6: ["Misty Escape"],
                10: ["Beguiling Defenses"],
                14: ["Dark Delerium"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 54
        "The Celestial": {
            "armors": [],
            "features": {
                1: ["Bonus Cantrips", "Expanded Spell List", "Healing Light"],
                6: ["Radiant Soul"],
                10: ["Celestial Resilience"],
                14: ["Searing Vengeance"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "The Fathomless": {
            "armors": [],
            "features": {
                1: ["Expanded Spell List", "Tentacle of the Deep", "Gift of the Sea"],
                6: ["Oceanic Soul", "Guardian Coil"],
                10: ["Grasping Tentacles"],
                14: ["Fathomless Plunge"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "The Fiend": {
            "armors": [],
            "features": {
                1: ["Dark One's Blessing", "Expanded Spell List"],
                6: ["Dark One's Own Luck"],
                10: ["Fiendish Resilience"],
                14: ["Hurl Through Hell"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "The Genie": {
            "armors": [],
            "features": {
                1: ["Expanded Spell List", "Genie's Vessel"],
                6: ["Elemental Gift"],
                10: ["Sanctuary Vessel"],
                14: ["Limited Wish"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "The Great Old One": {
            "armors": [],
            "features": {
                1: ["Awakened Mind", "Expanded Spell List"],
                6: ["Entropic Ward"],
                10: ["Thought Shield"],
                14: ["Create Thrall"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 55
        "The Hexblade": {
            "armors": [],
            "features": {
                1: ["Expanded Spell List", "Hexblade's Curse", "Hex Warrior"],
                6: ["Accursed Specter"],
                10: ["Armor of Hexes"],
                14: ["Master of Hexes"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "The Undying": {
            "armors": [],
            "features": {
                1: ["Expanded Spell List", "Among the Dead"],
                6: ["Defy Death"],
                10: ["Undying Nature"],
                14: ["Indestructible Life"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Thief": {
            "armors": [],
            "features": {
                3: ["Fast Hands", "Second-Story Work"],
                9: ["Supreme Sneak"],
                13: ["Use Magic Device"],
                17: ["Thief's Reflexes"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Trickery Domain": {
            "armors": [],
            "features": {
                1: ["Blessing of the Trickster"],
                2: ["Channel Divinity - Invoke Duplicity"],
                6: ["Channel Divinity - Cloak of Shadows"],
                8: ["Divine Strike"],
                17: ["Improved Duplicity"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Twilight Domain": {
            "armors": [],
            "features": {
                1: ["Vigilant Blessing"],
                2: ["Channel Divinity - Twilight Sanctuary"],
                6: ["Steps of Night"],
                8: ["Divine Strike"],
                17: ["Twilight Shroud"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "War Domain": {
            "armors": ["Heavy"],
            "features": {
                1: ["War Priest"],
                2: ["Channel Divinity - Guided Strike"],
                6: ["Channel Divinity - War God's Blessing"],
                8: ["Divine Strike"],
                17: ["Avatar of Battle"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        # XGtE pg 59
        "War Magic": {
            "armors": [],
            "features": {
                2: ["Arcane Deflection", "Tactical Wit"],
                6: ["Power Surge"],
                10: ["Durable Magic"],
                14: ["Deflecting Shroud"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Way of Mercy": {
            "armors": [],
            "features": {
                3: [
                    "Implements of Mercy",
                    "Hand of Healing",
                    "Hand of Harm",
                ],
                6: ["Physician's Touch"],
                11: ["Flurry of Healing and Harm"],
                17: ["Hand of Ultimate Mercy"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Way of Shadow": {
            "armors": [],
            "features": {
                3: ["Shadow Arts"],
                6: ["Shadow Step"],
                11: ["Cloak of Shadows"],
                17: ["Opportunist"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Way of the Astral Self": {
            "armors": [],
            "features": {
                3: ["Arms of the Astral Self"],
                6: ["Visage of the Astral Self"],
                11: ["Body of the Astral Self"],
                17: ["Awakened Astral Self"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 33
        "Way of the Drunken Master": {
            "armors": [],
            "features": {
                3: ["Bonus Proficiencies", "Drunken Technique"],
                6: ["Tipsy Sway"],
                11: ["Drunkard's Luck"],
                17: ["Intoxicated Frenzy"],
            },
            "languages": [],
            "skills": ["Performance"],
            "tools": [],
            "weapons": [],
        },
        "Way of the Four Elements": {
            "armors": [],
            "features": {
                3: [
                    "Disciple of the Elements",
                    "Elemental Attunement",
                    "Fangs of the Fire Snake",
                    "Fist of Four Thunders",
                    "Fist of Unbroken Air",
                    "Rush of the Gale Spirits",
                    "Shade the Flowing River",
                    "Sweeping Cinder Strike",
                    "Water Whip",
                ],
                6: [
                    "Clench of the North Wind",
                    "Gong of the Summit",
                ],
                11: [
                    "Eternal Mountain Defense",
                    "Flames of the Phoenix",
                    "Mist Stance",
                    "Ride the Wind",
                ],
                17: [
                    "Breath of Winter",
                    "River of Hungry Flame",
                    "Wave of Rolling Earth",
                ],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 34
        "Way of the Kensei": {
            "armors": [],
            "features": {
                3: ["Path of the Kensei (2 weapons)"],
                6: [
                    "One with the Blade",
                    "Path of the Kensei (3 weapons)",
                ],
                11: [
                    "Sharpen the Blade",
                    "Path of the Kensei (4 weapons)",
                ],
                17: [
                    "Unerring Accuracy",
                    "Path of the Kensei (5 weapons)",
                ],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Way of the Long Death": {
            "armors": [],
            "features": {
                3: ["Touch of Death"],
                6: ["Hour of Reaping"],
                11: ["Mastery of Death"],
                17: ["Touch of the Long Death"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Way of the Open Hand": {
            "armors": [],
            "features": {
                3: ["Open Hand Technique"],
                6: ["Wholeness of Body"],
                11: ["Tranquility"],
                17: ["Quivering Palm"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        # XGtE pg 35
        "Way of the Sun Soul": {
            "armors": [],
            "features": {
                3: ["Radiant Sun Bolt"],
                6: ["Searing Arc Strike"],
                11: ["Searing Sunburst"],
                17: ["Sun Shield"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Wild Magic": {
            "armors": [],
            "features": {
                1: ["Tides of Chaos", "Wild Magic Surge"],
                6: ["Bend Luck"],
                14: ["Controlled Chaos"],
                18: ["Spell Bombardment"],
            },
            "languages": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
    },
}
