subraces = {
    "subraces": {
        "Asmodeus": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Thaumaturgy"], 3: ["Hellish Rebuke"], 5: ["Darkness"]},
            "tools": [],
            "traits": ["Infernal Legacy"],
            "weapons": [],
        },
        "Baalzebul": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {
                1: ["Thaumaturgy"],
                3: ["Ray of Sickness"],
                5: ["Crown of Madness"],
            },
            "tools": [],
            "traits": ["Legacy of Maladomini"],
            "weapons": [],
        },
        "Deep": {
            "armors": [],
            "bonus": {"Dexterity": 1},
            "languages": ["Undercommon"],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Extra Language", "Superior Darkvision", "Stone Camouflage"],
            "weapons": [],
        },
        "Dispater": {
            "armors": [],
            "bonus": {"Dexterity": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Thaumaturgy"], 3: ["Disguise"], 5: ["Detect Thoughts"]},
            "tools": [],
            "traits": ["Legacy of Dis"],
            "weapons": [],
        },
        "Drow": {
            "armors": [],
            "bonus": {"Charisma": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Dancing Lights"], 3: ["Faerie Fire"], 5: ["Darkness"]},
            "tools": [],
            "traits": [
                "Drow Magic",
                "Drow Weapon Training",
                "Sunlight Sensitivity",
                "Superior Darkvision",
            ],
            "weapons": ["Hand Crossbow", "Rapier", "Shortsword"],
        },
        "Duergar": {
            "armors": [],
            "bonus": {"Strength": 1},
            "languages": ["Undercommon"],
            "resistances": ["Charm", "Illusion", "Paralysis"],
            "skills": [],
            "spells": {3: ["Enlarge/Reduce"], 5: ["Invisibility"]},
            "tools": [],
            "traits": [
                "Duergar Magic",
                "Duergar Resilience",
                "Extra Language",
                "Sunlight Sensitivity",
                "Superior Darkvision",
            ],
            "weapons": [],
        },
        "Eladrin": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Elf Weapon Training", "Fey Step"],
            "weapons": ["Longsword", "Shortsword", "Shortbow", "Longbow"],
        },
        "Fallen": {
            "armors": [],
            "bonus": {"Strength": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {3: ["Necrotic Shroud"]},
            "tools": [],
            "traits": ["Necrotic Shroud"],
            "weapons": [],
        },
        "Fierna": {
            "armors": [],
            "bonus": {"Wisdom": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Friends"], 3: ["Charm Person"], 5: ["Suggestion"]},
            "tools": [],
            "traits": ["Legacy of Phlegethos"],
            "weapons": [],
        },
        "Forest": {
            "armors": [],
            "bonus": {"Dexterity": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": ["Minor Illusion"],
            "tools": [],
            "traits": ["Natural Illusionist", "Speak with Small Beasts"],
            "weapons": [],
        },
        "Githyanki": {
            "armors": ["Light", "Medium"],
            "bonus": {"Strength": 2},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Mage Hand"], 3: ["Jump"], 5: ["Misty Step"]},
            "tools": [],
            "traits": ["Decadent Mastery", "Githyanki Psionics", "Martial Prodigy"],
            "weapons": ["Greatsword", "Longsword", "Shortsword"],
        },
        "Githzerai": {
            "armors": [],
            "bonus": {"Wisdom": 2},
            "languages": [],
            "resistances": ["Charm", "Fright"],
            "skills": [],
            "spells": {1: ["Mage Hand"], 3: ["Shield"], 5: ["Detect Thoughts"]},
            "tools": [],
            "traits": ["Githzerai Psionics", "Mental Discipline"],
            "weapons": [],
        },
        "Glasya": {
            "armors": [],
            "bonus": {"Dexterity": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {
                1: ["Minor Illusion"],
                3: ["Disguise Self"],
                5: ["Invisibility"],
            },
            "tools": [],
            "traits": ["Legacy of Malbolge"],
            "weapons": [],
        },
        "High": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Cantrip", "Elf Weapon Training", "Extra Language"],
            "weapons": ["Longsword", "Shortsword", "Shortbow", "Longbow"],
        },
        "Hill": {
            "armors": [],
            "bonus": {"Wisdom": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Dwarven Toughness"],
            "weapons": [],
        },
        "Levistus": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Ray of Frost"], 3: ["Armor of Agathys"], 5: ["Darkness"]},
            "tools": [],
            "traits": ["Legacy of Stygia"],
            "weapons": [],
        },
        "Lightfoot": {
            "armors": [],
            "bonus": {"Charisma": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Naturally Stealthy"],
            "weapons": [],
        },
        "Mammon": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {
                1: ["Mage Hand"],
                3: ["Tensor's Floating Disk"],
                5: ["Arcane Lock"],
            },
            "tools": [],
            "traits": ["Legacy of Minauros"],
            "weapons": [],
        },
        "Mephistopheles": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Mage Hand"], 3: ["Burning Hands"], 5: ["Flame Blade"]},
            "tools": [],
            "traits": ["Legacy of Cania"],
            "weapons": [],
        },
        "Mountain": {
            "armors": ["Light", "Medium"],
            "bonus": {"Strength": 2},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Dwarven Armor Training"],
            "weapons": [],
        },
        "Protector": {
            "armors": [],
            "bonus": {"Wisdom": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {3: ["Radiant Soul"]},
            "tools": [],
            "traits": ["Radiant Soul"],
            "weapons": [],
        },
        "Rock": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": ["Artisan's tools - Tinker's tools"],
            "traits": ["Artificer's Lore", "Tinker"],
            "weapons": [],
        },
        "Scourge": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {3: ["Radiant Consumption"]},
            "tools": [],
            "traits": ["Radiant Consumption"],
            "weapons": [],
        },
        "Sea": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": ["Aquan"],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Child of the Sea", "Friend of the Sea", "Sea Elf Training"],
            "weapons": ["Light Crossbow", "Net", "Spear", "Trident"],
        },
        "Shadar-kai": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": ["Necrotic"],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Blessing of the Raven Queen", "Necrotic Resistance"],
            "weapons": [],
        },
        "Stout": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": ["Poison"],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Stout Resilience"],
            "weapons": [],
        },
        "Wood": {
            "armors": [],
            "bonus": {"Wisdom": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Elf Weapon Training", "Fleet of Foot", "Mask of the Wild"],
            "weapons": ["Longsword", "Shortsword", "Shortbow", "Longbow"],
        },
        "Zariel": {
            "armors": [],
            "bonus": {"Strength": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Thaumaturgy"], 3: ["Searing"], 5: ["Branding Smite"]},
            "tools": [],
            "traits": ["Legacy of Avernus"],
            "weapons": [],
        },
    },
}
