backgrounds = {
    "backgrounds": {
        "Acolyte": {
            "ability": ["Intelligence", "Wisdom", "Charisma"],
            "feats": ["Magic Initiate"],
            "skills": ["Insight", "Religion"],
            "tools": ["Artisan's Tools - Cartographer's Supplies"],
        },
        "Artisan": {
            "ability": ["Strength", "Dexterity", "Intelligence"],
            "feats": ["Crafter"],
            "skills": ["Investigation", "Persuasion"],
            "tools": [
                "Artisan's Tools - Alchemists supplies",
                "Artisan's Tools - Brewer's supplies",
                "Artisan's Tools - Calligrapher's supplies",
                "Artisan's Tools - Carpenter's Tools",
                "Artisan's Tools - Cartographer's Tools",
                "Artisan's Tools - Cobbler's Tools",
                "Artisan's Tools - Cook's utensils",
                "Artisan's Tools - Glassblower's Tools",
                "Artisan's Tools - Jeweler's Tools",
                "Artisan's Tools - Leatherworker's Tools",
                "Artisan's Tools - Mason's Tools",
                "Artisan's Tools - Painter's supplies",
                "Artisan's Tools - Potter's Tools",
                "Artisan's Tools - Smith's Tools",
                "Artisan's Tools - Tinker's Tools",
                "Artisan's Tools - Weaver's Tools",
                "Artisan's Tools - Woodcarver's Tools",
            ],
        },
        "Charlatan": {
            "ability": ["Dexterity", "Constitution", "Charisma"],
            "feats": ["Skilled"],
            "skills": ["Deception", "Sleight of Hand"],
            "tools": ["Forgery Kit"],
        },
        "Criminal": {
            "ability": ["Dexterity", "Constitution", "Intelligence"],
            "feats": ["Alert"],
            "skills": ["Deception", "Stealth"],
            "tools": ["Thieves' Tools"],
        },
        "Entertainer": {
            "ability": ["Strength", "Dexterity", "Charisma"],
            "feats": ["Musician"],
            "skills": ["Acrobatics", "Performance"],
            "tools": [
                "Musical Instrument - Bagpipes",
                "Musical Instrument - Birdpipes",
                "Musical Instrument - Drum",
                "Musical Instrument - Dulcimer",
                "Musical Instrument - Flute",
                "Musical Instrument - Glaur",
                "Musical Instrument - Hand Drum",
                "Musical Instrument - Longhorn",
                "Musical Instrument - Lute",
                "Musical Instrument - Lyre",
                "Musical Instrument - Horn",
                "Musical Instrument - Pan flute",
                "Musical Instrument - Shawm",
                "Musical Instrument - Songhorn",
                "Musical Instrument - Tantan",
                "Musical Instrument - Thelarr",
                "Musical Instrument - Tocken",
                "Musical Instrument - Viol",
                "Musical Instrument - Wargong",
                "Musical Instrument - Yarting",
                "Musical Instrument - Zulkoon",
            ],
        },
        "Farmer": {
            "ability": ["Strength", "Constitution", "Wisdom"],
            "feats": ["Tough"],
            "skills": ["Animal Handling", "Nature"],
            "tools": ["Artisan's Tools - Carpenter's Tools"],
        },
        "Guard": {
            "ability": ["Strength", "Intelligence", "Wisdom"],
            "feats": ["Alert"],
            "skills": ["Athletics", "Perception"],
            "tools": [
                "Gaming Set - Dice Set",
                "Gaming Set - Dragonchess Set",
                "Gaming Set - Playing card Set",
                "Gaming Set - Three-Dragon Ante Set",
            ],
        },
        "Guide": {
            "ability": ["Dexterity", "Constitution", "Wisdom"],
            "feats": ["Magic Initiate"],
            "skills": ["Stealth", "Survival"],
            "tools": [
                "Artisan's Tools - Cartographer's Tools",
            ],
        },
        "Hermit": {
            "ability": ["Constitution", "Wisdom", "Charisma"],
            "feats": ["Healer"],
            "skills": ["Medicine", "Religion"],
            "tools": ["Herbalism kit"],
        },
        "Merchant": {
            "ability": ["Constitution", "Intelligence", "Charisma"],
            "feats": ["Lucky"],
            "skills": ["Animal Handling", "Persuasion"],
            "tools": ["Navigator's Tools"],
        },
        "Noble": {
            "ability": ["Strength", "Intelligence", "Charisma"],
            "feats": ["Skilled"],
            "skills": ["History", "Persuasion"],
            "tools": [
                "Gaming Set - Dice Set",
                "Gaming Set - Dragonchess Set",
                "Gaming Set - Playing card Set",
                "Gaming Set - Three-Dragon Ante Set",
            ],
        },
        "Sage": {
            "ability": ["Constitution", "Intelligence", "Wisdom"],
            "feats": ["Magic Initiate"],
            "skills": ["Arcana", "History"],
            "tools": ["Artisan's Tools - Cartographer's Supplies"],
        },
        "Sailor": {
            "ability": ["Strength", "Dexterity", "Wisdom"],
            "feats": ["Tavern Brawler"],
            "skills": ["Athletics", "Perception"],
            "tools": [
                "Gaming Set - Dice Set",
                "Gaming Set - Dragonchess Set",
                "Gaming Set - Playing card Set",
                "Gaming Set - Three-Dragon Ante Set",
            ],
        },
        "Scribe": {
            "ability": ["Dexterity", "Intelligence", "Wisdom"],
            "feats": ["Skilled"],
            "skills": ["Investigation", "Perception"],
            "tools": ["Artisan's Tools - Cartographer's Supplies"],
        },
        "Soldier": {
            "ability": ["Strength", "Dexterity", "Constitution"],
            "feats": ["Savage Attacker"],
            "skills": ["Athletics", "Intimidation"],
            "tools": ["Artisan's Tools - Cartographer's Supplies"],
        },
        "Wayfarer": {
            "ability": ["Dexterity", "Wisdom", "Charisma"],
            "feats": ["Lucky"],
            "skills": ["Insight", "Stealth"],
            "tools": ["Thieves' Tools"],
        },
    },
}
