classes = {
    "classes": {
        "Barbarian": {
            "armors": ["Light", "Medium", "Shield"],
            "cantrips": {},
            "features": {
                1: ["Rage", "Unarmored Defense", "Weapon Mastery"],
                2: ["Danger Sense", "Reckless Attack"],
                3: ["Barbarian Subclass", "Primal Knowledge"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack", "Fast Movement"],
                7: ["Feral Instinct", "Instinctive Pounce"],
                8: ["Ability Score Improvement"],
                9: ["Brutal Strike"],
                11: ["Relentless Rage"],
                12: ["Ability Score Improvement"],
                13: ["Improved Brutal Strike"],
                15: ["Persistent Rage"],
                16: ["Ability Score Improvement"],
                17: ["Improved Brutal Strike"],
                18: ["Indomitable Might"],
                19: ["Epic Boon"],
                20: ["Primal Champion"],
            },
            "hit_die": 12,
            "prepared_spells": {},
            "savingthrows": ["Constitution", "Strength"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Intimidation",
                "Nature",
                "Perception",
                "Survival",
            ],
            "spell_slots": {},
            "subclasses": [
                "Path of the Berserker",
                "Path of the Wild Heart",
                "Path of the World Tree",
                "Path of the Zealot",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Bard": {
            "armors": ["Light"],
            "cantrips": {
                1: 2,
                2: 2,
                3: 2,
                4: 3,
                5: 3,
                6: 3,
                7: 3,
                8: 3,
                9: 3,
                10: 4,
                11: 4,
                12: 4,
                13: 4,
                14: 4,
                15: 4,
                16: 4,
                17: 4,
                18: 4,
                19: 4,
                20: 4,
            },
            "features": {
                1: ["Bardic Inspiration", "Spellcasting"],
                2: ["Expertise", "Jack of All Trades"],
                3: ["Bard Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Font of Inspiration"],
                7: ["Countercharm"],
                8: ["Ability Score Improvement"],
                9: ["Expertise"],
                10: ["Magical Secrets"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                18: ["Superior Inspiration"],
                19: ["Epic Boon"],
                20: ["Words of Creation"],
            },
            "hit_die": 8,
            "prepared_spells": {
                1: 4,
                2: 5,
                3: 6,
                4: 7,
                5: 8,
                6: 9,
                7: 10,
                8: 11,
                9: 12,
                10: 14,
                11: 15,
                12: 15,
                13: 16,
                14: 18,
                15: 19,
                16: 19,
                17: 20,
                18: 22,
                19: 22,
                20: 22,
            },
            "savingthrows": ["Charisma", "Dexterity"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Arcana",
                "Athletics",
                "Deception",
                "History",
                "Insight",
                "Intimidation",
                "Investigation",
                "Medicine",
                "Nature",
                "Perception",
                "Performance",
                "Persuasion",
                "Religion",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "spell_slots": {
                1: [2],
                2: [3],
                3: [4, 2],
                4: [4, 3],
                5: [4, 3, 2],
                6: [4, 3, 3],
                7: [4, 3, 3, 1],
                8: [4, 3, 3, 2],
                9: [4, 3, 3, 3, 1],
                10: [4, 3, 3, 3, 2],
                11: [4, 3, 3, 3, 2, 1],
                12: [4, 3, 3, 3, 2, 1],
                13: [4, 3, 3, 3, 2, 1, 1],
                14: [4, 3, 3, 3, 2, 1, 1],
                15: [4, 3, 3, 3, 2, 1, 1, 1],
                16: [4, 3, 3, 3, 2, 1, 1, 1],
                17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
                18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
                19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
                20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
            },
            "subclasses": [
                "College of Dance",
                "College of Glamour",
                "College of Lore",
                "College of Valor",
            ],
            "tools": [
                "Musical Instrument - Bagpipes",
                "Musical Instrument - Birdpipes",
                "Musical Instrument - Drum",
                "Musical Instrument - Dulcimer",
                "Musical Instrument - Flute",
                "Musical Instrument - Glaur",
                "Musical Instrument - Hand Drum",
                "Musical Instrument - Longhorn",
                "Musical Instrument - Lute",
                "Musical Instrument - Lyre",
                "Musical Instrument - Horn",
                "Musical Instrument - Pan flute",
                "Musical Instrument - Shawm",
                "Musical Instrument - Songhorn",
                "Musical Instrument - Tantan",
                "Musical Instrument - Thelarr",
                "Musical Instrument - Tocken",
                "Musical Instrument - Viol",
                "Musical Instrument - Wargong",
                "Musical Instrument - Yarting",
                "Musical Instrument - Zulkoon",
            ],
            "weapons": ["Simple"],
        },
        "Cleric": {
            "armors": ["Light", "Medium", "Shield"],
            "cantrips": {
                1: 3,
                2: 3,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 4,
                8: 4,
                9: 4,
                10: 5,
                11: 5,
                12: 5,
                13: 5,
                14: 5,
                15: 5,
                16: 5,
                17: 5,
                18: 5,
                19: 5,
                20: 5,
            },
            "features": {
                1: ["Divine Order", "Spellcasting"],
                2: ["Channel Divinity"],
                3: ["Cleric Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Sear Undead"],
                7: ["Blessed Strikes"],
                8: ["Ability Score Improvement"],
                10: ["Divine Intervention"],
                12: ["Ability Score Improvement"],
                14: ["Improved Blessed Strikes"],
                16: ["Ability Score Improvement"],
                19: ["Epic Boon"],
                20: ["Greater Divine Intervention"],
            },
            "hit_die": 8,
            "prepared_spells": {
                1: 4,
                2: 5,
                3: 6,
                4: 7,
                5: 9,
                6: 10,
                7: 11,
                8: 12,
                9: 14,
                10: 15,
                11: 16,
                12: 16,
                13: 17,
                14: 17,
                15: 18,
                16: 18,
                17: 19,
                18: 20,
                19: 21,
                20: 22,
            },
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": ["History", "Insight", "Medicine", "Persuasion", "Religion"],
            "spell_slots": {
                1: [2],
                2: [3],
                3: [4, 2],
                4: [4, 3],
                5: [4, 3, 2],
                6: [4, 3, 3],
                7: [4, 3, 3, 1],
                8: [4, 3, 3, 2],
                9: [4, 3, 3, 3, 1],
                10: [4, 3, 3, 3, 2],
                11: [4, 3, 3, 3, 2, 1],
                12: [4, 3, 3, 3, 2, 1],
                13: [4, 3, 3, 3, 2, 1, 1],
                14: [4, 3, 3, 3, 2, 1, 1],
                15: [4, 3, 3, 3, 2, 1, 1, 1],
                16: [4, 3, 3, 3, 2, 1, 1, 1],
                17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
                18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
                19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
                20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
            },
            "subclasses": [
                "Life Domain",
                "Light Domain",
                "Trickery Domain",
                "War Domain",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Druid": {
            "armors": ["Light", "Shield"],
            "cantrips": {
                1: 2,
                2: 2,
                3: 2,
                4: 3,
                5: 3,
                6: 3,
                7: 3,
                8: 3,
                9: 3,
                10: 4,
                11: 4,
                12: 4,
                13: 4,
                14: 4,
                15: 4,
                16: 4,
                17: 4,
                18: 4,
                19: 4,
                20: 4,
            },
            "features": {
                1: ["Druidic", "Primal Order", "Spellcasting"],
                2: ["Wild Companion", "Wild Shape"],
                3: ["Druid Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Wild Resurgence"],
                7: ["Elemental Fury"],
                8: ["Ability Score Improvement"],
                12: ["Ability Score Improvement"],
                15: ["Improved Elemental Fury"],
                16: ["Ability Score Improvement"],
                18: ["Beast Spells"],
                19: ["Epic Boon"],
                20: ["Archdruid"],
            },
            "hit_die": 8,
            "prepared_spells": {
                1: 4,
                2: 5,
                3: 6,
                4: 7,
                5: 9,
                6: 10,
                7: 11,
                8: 12,
                9: 14,
                10: 15,
                11: 16,
                12: 16,
                13: 17,
                14: 17,
                15: 18,
                16: 18,
                17: 19,
                18: 20,
                19: 21,
                20: 22,
            },
            "savingthrows": ["Intelligence", "Wisdom"],
            "skills": [
                "Animal Handling",
                "Arcana",
                "Insight",
                "Medicine",
                "Nature",
                "Perception",
                "Religion",
                "Survival",
            ],
            "spell_slots": {
                1: [2],
                2: [3],
                3: [4, 2],
                4: [4, 3],
                5: [4, 3, 2],
                6: [4, 3, 3],
                7: [4, 3, 3, 1],
                8: [4, 3, 3, 2],
                9: [4, 3, 3, 3, 1],
                10: [4, 3, 3, 3, 2],
                11: [4, 3, 3, 3, 2, 1],
                12: [4, 3, 3, 3, 2, 1],
                13: [4, 3, 3, 3, 2, 1, 1],
                14: [4, 3, 3, 3, 2, 1, 1],
                15: [4, 3, 3, 3, 2, 1, 1, 1],
                16: [4, 3, 3, 3, 2, 1, 1, 1],
                17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
                18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
                19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
                20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
            },
            "subclasses": [
                "Circle of the Land",
                "Circle of the Moon",
                "Circle of the Sea",
                "Circle of the Stars",
            ],
            "tools": ["Herbalism Kit"],
            "weapons": [
                "Simple",
            ],
        },
        "Fighter": {
            "armors": ["Light", "Medium", "Heavy", "Shield"],
            "cantrips": {
                1: 0,
                2: 0,
                3: 2,
                4: 2,
                5: 2,
                6: 2,
                7: 2,
                8: 2,
                9: 2,
                10: 3,
                11: 3,
                12: 3,
                13: 3,
                14: 3,
                15: 3,
                16: 3,
                17: 3,
                18: 3,
                19: 3,
                20: 3,
            },
            "features": {
                1: ["Fighting Style", "Second Wind", "Weapon Mastery"],
                2: ["Action Surge (one use)", "Tactical Mind"],
                3: ["Fighter Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack", "Tactical Shift"],
                6: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                9: ["Indomitable (one use)", "Tactical Master"],
                11: ["Two Extra Attacks"],
                12: ["Ability Score Improvement"],
                13: ["Indomitable (two uses)", "Studied Attacks"],
                14: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                17: ["Action Surge (two uses)", "Indomitable (three uses)"],
                19: ["Epic Boon"],
                20: ["Three Extra Attacks"],
            },
            "hit_die": 10,
            "prepared_spells": {
                1: 0,
                2: 0,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 5,
                8: 6,
                9: 6,
                10: 7,
                11: 8,
                12: 8,
                13: 9,
                14: 10,
                15: 10,
                16: 11,
                17: 11,
                18: 11,
                19: 12,
                20: 13,
            },
            "savingthrows": ["Constitution", "Strength"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Athletics",
                "History",
                "Insight",
                "Intimidation",
                "Perception",
                "Survival",
            ],
            "spell_slots": {
                1: [0],
                2: [0],
                3: [2],
                4: [3],
                5: [3],
                6: [3],
                7: [4, 2],
                8: [4, 2],
                9: [4, 2],
                10: [4, 3],
                11: [4, 3],
                12: [4, 3],
                13: [4, 3, 2],
                14: [4, 3, 2],
                15: [4, 3, 2],
                16: [4, 3, 3],
                17: [4, 3, 3],
                18: [4, 3, 3],
                19: [4, 3, 3, 1],
                20: [4, 3, 3, 1],
            },
            "subclasses": [
                "Battle Master",
                "Champion",
                "Eldritch Knight",
                "Psi Warrior",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Monk": {
            "armors": [],
            "cantrips": {},
            "features": {
                1: ["Martial Arts", "Unarmored Defense"],
                2: ["Monk's Focus", "Unarmored Movement", "Uncanny Metabolism"],
                3: ["Deflect Attacks", "Monk Subclass"],
                4: ["Ability Score Improvement", "Slow Fall"],
                5: ["Extra Attack", "Stunning Strike"],
                6: ["Empowered Strikes"],
                7: ["Evasion"],
                8: ["Ability Score Improvement"],
                9: ["Acrobatic Movement"],
                10: ["Heightened Focus", "Self-Restoration"],
                12: ["Ability Score Improvement"],
                13: ["Deflect Energy"],
                14: ["Disciplined Survivor"],
                15: ["Perfect Focus"],
                16: ["Ability Score Improvement"],
                18: ["Superior Defense"],
                19: ["Epic Boon"],
                20: ["Body and Mind"],
            },
            "hit_die": 8,
            "prepared_spells": {},
            "savingthrows": ["Dexterity", "Strength"],
            "skills": [
                "Acrobatics",
                "Athletics",
                "History",
                "Insight",
                "Religion",
                "Stealth",
            ],
            "spell_slots": {},
            "subclasses": [
                "Warrior of Mercy",
                "Warrior of Shadow",
                "Warrior of the Elements",
                "Warrior of the Open Hand",
            ],
            "tools": [
                "Artisan's Tools - Alchemists Supplies",
                "Artisan's Tools - Brewer's Supplies",
                "Artisan's Tools - Calligrapher's Supplies",
                "Artisan's Tools - Carpenter's Tools",
                "Artisan's Tools - Cartographer's Tools",
                "Artisan's Tools - Cobbler's Tools",
                "Artisan's Tools - Cook's utensils",
                "Artisan's Tools - Glassblower's Tools",
                "Artisan's Tools - Jeweler's Tools",
                "Artisan's Tools - Leatherworker's Tools",
                "Artisan's Tools - Mason's Tools",
                "Artisan's Tools - Painter's Supplies",
                "Artisan's Tools - Potter's Tools",
                "Artisan's Tools - Smith's Tools",
                "Artisan's Tools - Tinker's Tools",
                "Artisan's Tools - Weaver's Tools",
                "Artisan's Tools - Woodcarver's Tools",
                "Musical Instrument - Bagpipes",
                "Musical Instrument - Birdpipes",
                "Musical Instrument - Drum",
                "Musical Instrument - Dulcimer",
                "Musical Instrument - Flute",
                "Musical Instrument - Glaur",
                "Musical Instrument - Hand Drum",
                "Musical Instrument - Longhorn",
                "Musical Instrument - Lute",
                "Musical Instrument - Lyre",
                "Musical Instrument - Horn",
                "Musical Instrument - Pan flute",
                "Musical Instrument - Shawm",
                "Musical Instrument - Songhorn",
                "Musical Instrument - Tantan",
                "Musical Instrument - Thelarr",
                "Musical Instrument - Tocken",
                "Musical Instrument - Viol",
                "Musical Instrument - Wargong",
                "Musical Instrument - Yarting",
                "Musical Instrument - Zulkoon",
            ],
            "weapons": ["Simple", "Martial (Light)"],
        },
        "Paladin": {
            "armors": ["Light", "Medium", "Heavy", "Shield"],
            "cantrips": {},
            "features": {
                1: ["Lay on Hands", "Spellcasting", "Weapon Mastery"],
                2: ["Fighting Style", "Paladin's Smite"],
                3: ["Channel Divinity", "Paladin Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack", "Faithful Steed"],
                6: ["Aura of Protection"],
                8: ["Ability Score Improvement"],
                9: ["Abjure Foes"],
                10: ["Aura of Courage"],
                11: ["Radiant Strikes"],
                12: ["Ability Score Improvement"],
                14: ["Restoring Touch"],
                16: ["Ability Score Improvement"],
                18: ["Aura Expansion"],
                19: ["Epic Boon"],
            },
            "hit_die": 10,
            "prepared_spells": {
                1: 2,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 6,
                7: 7,
                8: 7,
                9: 9,
                10: 9,
                11: 10,
                12: 10,
                13: 11,
                14: 11,
                15: 12,
                16: 12,
                17: 14,
                18: 14,
                19: 15,
                20: 15,
            },
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": [
                "Athletics",
                "Insight",
                "Intimidation",
                "Medicine",
                "Persuasion",
                "Religion",
            ],
            "spell_slots": {
                1: [0],
                2: [2],
                3: [3],
                4: [3],
                5: [4, 2],
                6: [4, 2],
                7: [4, 3],
                8: [4, 3],
                9: [4, 3, 2],
                10: [4, 3, 2],
                11: [4, 3, 3],
                12: [4, 3, 3],
                13: [4, 3, 3, 1],
                14: [4, 3, 3, 1],
                15: [4, 3, 3, 2],
                16: [4, 3, 3, 2],
                17: [4, 3, 3, 3, 1],
                18: [4, 3, 3, 3, 1],
                19: [4, 3, 3, 3, 2],
                20: [4, 3, 3, 3, 2],
            },
            "subclasses": [
                "Oath of Devotion",
                "Oath of Glory",
                "Oath of the Ancients",
                "Oath of Vengeance",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Ranger": {
            "armors": ["Light", "Medium", "Shield"],
            "cantrips": {},
            "features": {
                1: ["Favored Enemy", "Spellcasting", "Weapon Mastery"],
                2: ["Deft Explorer", "Fighting Style"],
                3: ["Ranger Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack"],
                6: ["Roving"],
                8: ["Ability Score Improvement"],
                9: ["Expertise"],
                10: ["Tireless"],
                12: ["Ability Score Improvement"],
                13: ["Relentless Hunter"],
                14: ["Nature's Veil"],
                16: ["Ability Score Improvement"],
                17: ["Precise Hunter"],
                18: ["Feral Senses"],
                19: ["Epic Boon"],
                20: ["Foe Slayer"],
            },
            "hit_die": 10,
            "prepared_spells": {
                1: 2,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 6,
                7: 7,
                8: 7,
                9: 9,
                10: 9,
                11: 10,
                12: 10,
                13: 11,
                14: 11,
                15: 12,
                16: 12,
                17: 14,
                18: 14,
                19: 15,
                20: 15,
            },
            "savingthrows": ["Dexterity", "Strength"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Insight",
                "Investigation",
                "Nature",
                "Perception",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "spell_slots": {
                1: [2],
                2: [2],
                3: [3],
                4: [3],
                5: [4,2],
                6: [4,2],
                7: [4,3],
                8: [4,3],
                9: [4,3,2],
                10: [4,3,2],
                11: [4,3,3],
                12: [4,3,3],
                13: [4,3,3,1],
                14: [4,3,3,1],
                15: [4,3,3,2],
                16: [4,3,3,2],
                17: [4,3,3,3,1],
                18: [4,3,3,3,1],
                19: [4,3,3,3,2],
                20: [4,3,3,3,2],
            },
            "subclasses": [
                "Beast Master",
                "Fey Wanderer",
                "Gloom Stalker",
                "Hunter",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Rogue": {
            "armors": ["Light"],
            "cantrips": {
                1: 0,
                2: 0,
                3: 3,
                4: 3,
                5: 3,
                6: 3,
                7: 3,
                8: 3,
                9: 3,
                10: 4,
                11: 4,
                12: 4,
                13: 4,
                14: 4,
                15: 4,
                16: 4,
                17: 4,
                18: 4,
                19: 4,
                20: 4,
            },
            "features": {
                1: ["Expertise", "Sneak Attack", "Thieves' Cant", "Weapon Mastery"],
                2: ["Cunning Action"],
                3: ["Rogue Subclass", "Steady Aim"],
                4: ["Ability Score Improvement"],
                5: ["Cunning Strike", "Uncanny Dodge"],
                7: ["Evasion", "Reliable Talent"],
                8: ["Ability Score Improvement"],
                10: ["Ability Score Improvement"],
                11: ["Improved Cunning Strike"],
                12: ["Ability Score Improvement"],
                14: ["Devious Strikes"],
                15: ["Slippery Mind"],
                16: ["Ability Score Improvement"],
                18: ["Elusive"],
                19: ["Epic Boon"],
                20: ["Stroke of Luck"],
            },
            "hit_die": 8,
            "prepared_spells": {
                1: 0,
                2: 0,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 5,
                8: 6,
                9: 6,
                10: 7,
                11: 8,
                12: 8,
                13: 9,
                14: 10,
                15: 10,
                16: 11,
                17: 11,
                18: 11,
                19: 12,
                20: 13,
            },
            "savingthrows": ["Dexterity", "Intelligence"],
            "skills": [
                "Acrobatics",
                "Athletics",
                "Deception",
                "Insight",
                "Intimidation",
                "Investigation",
                "Perception",
                "Performance",
                "Persuasion",
                "Sleight of Hand",
                "Stealth",
            ],
            "spell_slots": {
                1: [0],
                2: [0],
                3: [2],
                4: [3],
                5: [3],
                6: [3],
                7: [4, 2],
                8: [4, 2],
                9: [4, 2],
                10: [4, 3],
                11: [4, 3],
                12: [4, 3],
                13: [4, 3, 2],
                14: [4, 3, 2],
                15: [4, 3, 2],
                16: [4, 3, 3],
                17: [4, 3, 3],
                18: [4, 3, 3],
                19: [4, 3, 3, 1],
                20: [4, 3, 3, 1],
            },
            "subclasses": [
                "Arcane Trickster",
                "Assassin",
                "Soulknife",
                "Thief",
            ],
            "tools": ["Thieves' Tools"],
            "weapons": ["Simple", "Martial (Finesse, Light)"],
        },
        "Sorcerer": {
            "armors": [],
            "cantrips": {
                1: 4,
                2: 4,
                3: 4,
                4: 5,
                5: 5,
                6: 5,
                7: 5,
                8: 5,
                9: 5,
                10: 6,
                11: 6,
                12: 6,
                13: 6,
                14: 6,
                15: 6,
                16: 6,
                17: 6,
                18: 6,
                19: 6,
                20: 6,
            },
            "features": {
                1: ["Innate Sorcery", "Spellcasting"],
                2: ["Font of Magic", "Metamagic"],
                3: ["Sorcerer Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Sorcerous Restoration"],
                7: ["Sorcery Incarnate"],
                8: ["Ability Score Improvement"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                19: ["Epic Boon"],
                20: ["Arcane Apotheosis"],
            },
            "hit_die": 6,
            "prepared_spells": {
                1: 2,
                2: 4,
                3: 6,
                4: 7,
                5: 9,
                6: 10,
                7: 11,
                8: 12,
                9: 14,
                10: 15,
                11: 16,
                12: 16,
                13: 17,
                14: 17,
                15: 18,
                16: 18,
                17: 19,
                18: 20,
                19: 21,
                20: 22,
            },
            "savingthrows": ["Charisma", "Constitution"],
            "skills": [
                "Arcana",
                "Deception",
                "Insight",
                "Intimidation",
                "Persuasion",
                "Religion",
            ],
            "spell_slots": {
                1: [2],
                2: [3],
                3: [4, 2],
                4: [4, 3],
                5: [4, 3, 2],
                6: [4, 3, 3],
                7: [4, 3, 3, 1],
                8: [4, 3, 3, 2],
                9: [4, 3, 3, 3, 1],
                10: [4, 3, 3, 3, 2],
                11: [4, 3, 3, 3, 2, 1],
                12: [4, 3, 3, 3, 2, 1],
                13: [4, 3, 3, 3, 2, 1, 1],
                14: [4, 3, 3, 3, 2, 1, 1],
                15: [4, 3, 3, 3, 2, 1, 1, 1],
                16: [4, 3, 3, 3, 2, 1, 1, 1],
                17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
                18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
                19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
                20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
            },
            "subclasses": [
                "Aberrant Sorcery",
                "Clockwork Sorcery",
                "Draconic Sorcery",
                "Wild Magic Sorcery",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Warlock": {
            "armors": ["Light"],
            "cantrips": {
                1: 2,
                2: 2,
                3: 2,
                4: 3,
                5: 3,
                6: 3,
                7: 3,
                8: 3,
                9: 3,
                10: 4,
                11: 4,
                12: 4,
                13: 4,
                14: 4,
                15: 4,
                16: 4,
                17: 4,
                18: 4,
                19: 4,
                20: 4,
            },
            "features": {
                1: ["Eldritch Invocations", "Pact Magic"],
                2: ["Magical Cunning"],
                3: ["Warlock Subclass"],
                4: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                9: ["Contact Patron"],
                11: ["Mystic Arcanum (level 6 spell)"],
                12: ["Ability Score Improvement"],
                13: ["Mystic Arcanum (level 7 spell)"],
                15: ["Mystic Arcanum (level 8 spell)"],
                16: ["Ability Score Improvement"],
                17: ["Mystic Arcanum (level 9 spell)"],
                19: ["Epic Boon"],
                20: ["Eldritch Master"],
            },
            "hit_die": 8,
            "prepared_spells": {
                1: 2,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 7,
                7: 8,
                8: 9,
                9: 10,
                10: 10,
                11: 11,
                12: 11,
                13: 12,
                14: 12,
                15: 13,
                16: 13,
                17: 14,
                18: 14,
                19: 15,
                20: 15,
            },
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": [
                "Arcana",
                "Deception",
                "History",
                "Intimidation",
                "Investigation",
                "Nature",
                "Religion",
            ],
            "spell_slots": {
                1: [1],
                2: [2],
                3: [2, 2],
                4: [2, 2],
                5: [2, 2, 2],
                6: [2, 2, 2],
                7: [2, 2, 2, 2],
                8: [2, 2, 2, 2],
                9: [2, 2, 2, 2, 2],
                10: [2, 2, 2, 2, 2],
                11: [3, 3, 3, 3, 3, 1],
                12: [3, 3, 3, 3, 3, 1],
                13: [3, 3, 3, 3, 3, 1, 1],
                14: [3, 3, 3, 3, 3, 1, 1],
                15: [3, 3, 3, 3, 3, 1, 1, 1],
                16: [3, 3, 3, 3, 3, 1, 1, 1],
                17: [4, 4, 4, 4, 4, 1, 1, 1, 1],
                18: [4, 4, 4, 4, 4, 1, 1, 1, 1],
                19: [4, 4, 4, 4, 4, 1, 1, 1, 1],
                20: [4, 4, 4, 4, 4, 1, 1, 1, 1],
            },
            "subclasses": [
                "Archfey Patron",
                "Celestial Patron",
                "Fiend Patron",
                "Great Old One Patron",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Wizard": {
            "armors": [],
            "cantrips": {
                1: 3,
                2: 3,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 4,
                8: 4,
                9: 4,
                10: 5,
                11: 5,
                12: 5,
                13: 5,
                14: 5,
                15: 5,
                16: 5,
                17: 5,
                18: 5,
                19: 5,
                20: 5,
            },
            "features": {
                1: ["Arcane Recovery", "Ritual Adept", "Spellcasting"],
                2: ["Scholar"],
                3: ["Wizard Subclass"],
                4: ["Ability Score Improvement"],
                5: ["Memorize Spell"],
                8: ["Ability Score Improvement"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                18: ["Spell Mastery"],
                19: ["Epic Boon"],
                20: ["Signature Spells"],
            },
            "hit_die": 6,
            "prepared_spells": {
                1: 4,
                2: 5,
                3: 6,
                4: 7,
                5: 9,
                6: 10,
                7: 11,
                8: 12,
                9: 14,
                10: 15,
                11: 16,
                12: 16,
                13: 17,
                14: 18,
                15: 19,
                16: 21,
                17: 22,
                18: 23,
                19: 24,
                20: 25,
            },
            "savingthrows": ["Intelligence", "Wisdom"],
            "skills": [
                "Arcana",
                "History",
                "Insight",
                "Investigation",
                "Medicine",
                "Religion",
            ],
            "spell_slots": {
                1: [2],
                2: [3],
                3: [4, 2],
                4: [4, 3],
                5: [4, 3, 2],
                6: [4, 3, 3],
                7: [4, 3, 3, 1],
                8: [4, 3, 3, 2],
                9: [4, 3, 3, 3, 1],
                10: [4, 3, 3, 3, 2],
                11: [4, 3, 3, 3, 2, 1],
                12: [4, 3, 3, 3, 2, 1],
                13: [4, 3, 3, 3, 2, 1, 1],
                14: [4, 3, 3, 3, 2, 1, 1],
                15: [4, 3, 3, 3, 2, 1, 1, 1],
                16: [4, 3, 3, 3, 2, 1, 1, 1],
                17: [4, 3, 3, 3, 2, 1, 1, 1, 1],
                18: [4, 3, 3, 3, 3, 1, 1, 1, 1],
                19: [4, 3, 3, 3, 3, 2, 1, 1, 1],
                20: [4, 3, 3, 3, 3, 2, 2, 1, 1],
            },
            "subclasses": [
                "Abjurer",
                "Diviner",
                "Evoker",
                "Illusionist",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
    },
}
