feats = {
    "feats": {
        "Ability Score Improvement": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Actor": {
            "ability": {"Charisma": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Alert": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Archery": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Athlete": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Blind Fighting": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Boon of Combat Prowess": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Dimensional Travel": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Energy Resistance": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Fate": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Fortitude": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Irresistible Offense": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Recovery": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Skill": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Speed": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Spell Recall": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": ["Spellcasting"],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of the Night Spirit": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Boon of Truesight": {
            "ability": {},
            "armors": [],
            "category": "Epic Boon",
            "features": [],
            "level": 19,
            "tools": [],
            "weapons": [],
        },
        "Charger": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Chef": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Crafter": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Crossbow Expert": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Crusher": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Defense": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Defensive Duelist": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Dual Wielder": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Dueling": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Durable": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Elemental Adept": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": ["Pact Magic", "Spellcasting"],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Fey-Touched": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Grappler": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Great Weapon Fighting": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Great Weapon Master": {
            "ability": {"Strength": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Healer": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Heavily Armored": {
            "ability": {},
            "armors": ["Medium"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Heavy Armor Master": {
            "ability": {},
            "armors": ["Heavy"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Inspiring Leader": {
            "ability": {"Wisdom": 13, "Charisma": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Interception": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Keen Mind": {
            "ability": {"Intelligence": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Lightly Armored": {
            "ability": {},
            "armors": ["Light", "Shields"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Lucky": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Mage Slayer": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Magic Initiate": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Martial Weapon Training": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Medium Armor Master": {
            "ability": {},
            "armors": ["Medium"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Moderately Armored": {
            "ability": {},
            "armors": ["Light"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Mounted Combatant": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Musician": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Observant": {
            "ability": {"Intelligence": 13, "Wisdom": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Piercer": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Poisoner": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Polearm Master": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Protection": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Resilient": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Ritual Caster": {
            "ability": {"Intelligence": 13, "Wisdom": 13, "Charisma": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Savage Attacker": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Sentinel": {
            "ability": {"Strength": 13, "Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Shadow-Touched": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Sharpshooter": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Shield Master": {
            "ability": {},
            "armors": ["Shield"],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Skilled": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Skill Expert": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Skulker": {
            "ability": {"Dexterity": 13},
            "armors": [],
            "features": [],
            "category": "General",
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Slasher": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Speedy": {
            "ability": {"Dexterity": 13, "Constitution": 13},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Spell Sniper": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": ["Spellcasting", "Pact Magic"],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Tavern Brawler": {
            "ability": {},
            "armors": [],
            "category": "Origin",
            "features": [],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Telekinetic": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Telepathic": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Thrown Weapon Fighting": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Tough": {
            "ability": {},
            "armors": [],
            "features": [],
            "category": "Origin",
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Two-Weapon Fighting": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "Unarmed Fighting": {
            "ability": {},
            "armors": [],
            "category": "Fighting Style",
            "features": ["Fighting Style"],
            "level": 1,
            "tools": [],
            "weapons": [],
        },
        "War Caster": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": ["Spellcasting", "Pact Magic"],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
        "Weapon Master": {
            "ability": {},
            "armors": [],
            "category": "General",
            "features": [],
            "level": 4,
            "tools": [],
            "weapons": [],
        },
    },
}
