classes = {
    "classes": {
        "Artificer": {
            "armors": ["Light", "Medium", "Shield"],
            "features": {
                1: ["Magical Tinkering", "Spellcasting"],
                2: ["Infuse Item"],
                3: ["Artificer Specialist", "The Right Tool for the Job"],
                4: ["Ability Score Improvement"],
                5: ["Artificer Specialist feature"],
                6: ["Tool Expertise"],
                7: ["Flash of Genius"],
                8: ["Ability Score Improvement"],
                9: ["Artificer Specialist feature"],
                11: ["Spell Storing Item"],
                12: ["Ability Score Improvement"],
                14: ["Magic Item Savant"],
                15: ["Artificer Specialist feature"],
                16: ["Ability Score Improvement"],
                18: ["Magic Item Master"],
                19: ["Ability Score Improvement"],
                20: ["Soul of Artifice"],
            },
            "gold": "5d4",
            "hit_die": 8,
            "languages": [],
            "savingthrows": ["Constitution", "Intelligence"],
            "skills": [
                "Arcana",
                "History",
                "Investigation",
                "Medicine",
                "Nature",
                "Perception",
                "Sleight of Hand",
            ],
            "spell_slots": {
                1: "2,2",
                2: "2,2",
                3: "2,3",
                4: "2,3",
                5: "2,4,2",
                6: "2,4,2",
                7: "2,4,3",
                8: "2,4,3",
                9: "2,4,3,2",
                10: "3,4,3,2",
                11: "3,4,3,3",
                12: "3,4,3,3",
                13: "3,4,3,3,1",
                14: "4,4,3,3,1",
                15: "4,4,3,3,2",
                16: "4,4,3,3,2",
                17: "4,4,3,3,3,1",
                18: "4,4,3,3,3,1",
                19: "4,4,3,3,3,2",
                20: "4,4,3,3,3,2",
            },
            "subclass": [
                "Alchemist",
                "Armorer",
                "Artillerist",
                "Battle Smith",
            ],
            "tools": ["Thieves' tools", "Artisan's tools - Tinker's tools"],
            "weapons": ["Simple"],
        },
        "Barbarian": {
            "armors": ["Light", "Medium", "Shield"],
            "features": {
                1: ["Rage", "Unarmored Defense"],
                2: ["Danger Sense", "Reckless Attack"],
                3: ["Primal Path"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack", "Fast Movement"],
                7: ["Feral Instinct"],
                8: ["Ability Score Improvement"],
                9: ["Brutal Critical"],
                11: ["Relentless Rage"],
                12: ["Ability Score Improvement"],
                13: ["Brutal Critical"],
                15: ["Persistent Rage"],
                16: ["Ability Score Improvement"],
                17: ["Brutal Critical"],
                18: ["Indomitable Might"],
                19: ["Ability Score Improvement"],
                20: ["Primal Champion"],
            },
            "gold": "2d4",
            "hit_die": 12,
            "languages": [],
            "savingthrows": ["Constitution", "Strength"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Intimidation",
                "Nature",
                "Perception",
                "Survival",
            ],
            "spell_slots": {},
            "subclass": [
                "Path of the Ancestral Guardian",
                "Path of the Battlerager",
                "Path of the Beast",
                "Path of the Berserker",
                "Path of the Storm Herald",
                "Path of the Totem Warrior",
                "Path of the Zealot",
                "Path of Wild Magic",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Bard": {
            "armors": ["Light"],
            "features": {
                1: ["Bardic Inspiration", "Spellcasting"],
                2: ["Jack of All Trades", "Song of Rest"],
                3: ["Bard College", "Expertise"],
                4: ["Ability Score Improvement"],
                5: ["Bardic Inspiration", "Font of Inspiration"],
                6: ["Countercharm"],
                8: ["Ability Score Improvement"],
                9: ["Song of Rest"],
                10: ["Bardic Inspiration", "Expertise", "Magical Secrets"],
                12: ["Ability Score Improvement"],
                13: ["Song of Rest"],
                14: ["Magical Secrets"],
                15: ["Bardic Inspiration"],
                16: ["Ability Score Improvement"],
                17: ["Song of Rest"],
                18: ["Magical Secrets"],
                19: ["Ability Score Improvement"],
                20: ["Superior Inspiration"],
            },
            "gold": "5d4",
            "hit_die": 8,
            "languages": [],
            "savingthrows": ["Charisma", "Dexterity"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Arcana",
                "Athletics",
                "Deception",
                "History",
                "Insight",
                "Intimidation",
                "Investigation",
                "Medicine",
                "Nature",
                "Perception",
                "Performance",
                "Persuasion",
                "Religion",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "spells_known": {
                1: 4,
                2: 5,
                3: 6,
                4: 7,
                5: 8,
                6: 9,
                7: 10,
                8: 11,
                9: 12,
                10: 14,
                11: 15,
                12: 15,
                13: 16,
                14: 18,
                15: 19,
                16: 19,
                17: 20,
                18: 22,
                19: 22,
                20: 22,
            },
            "spell_slots": {
                1: "2,2",
                2: "2,3",
                3: "2,4,2",
                4: "3,4,3",
                5: "3,4,3,2",
                6: "3,4,3,3",
                7: "3,4,3,3,1",
                8: "3,4,3,3,2",
                9: "3,4,3,3,3,1",
                10: "4,4,3,3,3,2",
                11: "4,4,3,3,3,2,1",
                12: "4,4,3,3,3,2,1",
                13: "4,4,3,3,3,2,1,1",
                14: "4,4,3,3,3,2,1,1",
                15: "4,4,3,3,3,2,1,1,1",
                16: "4,4,3,3,3,2,1,1,1",
                17: "4,4,3,3,3,2,1,1,1,1",
                18: "4,4,3,3,3,3,1,1,1,1",
                19: "4,4,3,3,3,3,2,1,1,1",
                20: "4,4,3,3,3,3,2,2,1,1",
            },
            "subclass": [
                "College of Creation",
                "College of Eloquence",
                "College of Glamour",
                "College of Lore",
                "College of Swords",
                "College of Valor",
                "College of Whispers",
            ],
            "tools": [],
            "weapons": ["Simple", "Hand Crossbow", "Longsword", "Rapier", "Shortsword"],
        },
        "Cleric": {
            "armors": ["Light", "Medium", "Shield"],
            "features": {
                1: ["Divine Domain", "Spellcasting"],
                2: ["Channel Divinity - Turn Undead"],
                4: ["Ability Score Improvement"],
                5: ["Destroy Undead"],
                8: ["Ability Score Improvement", "Destroy Undead"],
                10: ["Divine Intervention"],
                11: ["Destroy Undead"],
                12: ["Ability Score Improvement"],
                14: ["Destroy Undead"],
                16: ["Ability Score Improvement"],
                17: ["Destroy Undead"],
                19: ["Ability Score Improvement"],
                20: ["Divine Intervention"],
            },
            "gold": "5d4",
            "hit_die": 8,
            "languages": [],
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": ["History", "Insight", "Medicine", "Persuasion", "Religion"],
            "spell_slots": {
                1: "3,2",
                2: "3,3",
                3: "3,4,2",
                4: "4,4,3",
                5: "4,4,3,2",
                6: "4,4,3,3",
                7: "4,4,3,3,1",
                8: "4,4,3,3,2",
                9: "4,4,3,3,3,1",
                10: "5,4,3,3,3,2",
                11: "5,4,3,3,3,2,1",
                12: "5,4,3,3,3,2,1",
                13: "5,4,3,3,3,2,1,1",
                14: "5,4,3,3,3,2,1,1",
                15: "5,4,3,3,3,2,1,1,1",
                16: "5,4,3,3,3,2,1,1,1",
                17: "5,4,3,3,3,2,1,1,1,1",
                18: "5,4,3,3,3,3,1,1,1,1",
                19: "5,4,3,3,3,3,2,1,1,1",
                20: "5,4,3,3,3,3,2,2,1,1",
            },
            "subclass": [
                "Arcana Domain",
                "Death Domain",
                "Forge Domain",
                "Grave Domain",
                "Knowledge Domain",
                "Life Domain",
                "Light Domain",
                "Nature Domain",
                "Order Domain",
                "Peace Domain",
                "Tempest Domain",
                "Trickery Domain",
                "Twilight Domain",
                "War Domain",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Druid": {
            "armors": ["Light", "Medium", "Shield"],
            "features": {
                1: ["Spellcasting"],
                2: ["Druidic Circle", "Wild Shape"],
                4: ["Ability Score Improvement", "Wild Shape"],
                8: ["Ability Score Improvement", "Wild Shape"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                18: ["Beast Spells", "Timeless Body"],
                19: ["Ability Score Improvement"],
                20: ["Archdruid"],
            },
            "gold": "2d4",
            "hit_die": 8,
            "languages": ["Druidic"],
            "savingthrows": ["Intelligence", "Wisdom"],
            "skills": [
                "Animal Handling",
                "Arcana",
                "Insight",
                "Medicine",
                "Nature",
                "Perception",
                "Religion",
                "Survival",
            ],
            "spell_slots": {
                1: "2,2",
                2: "2,3",
                3: "2,4,2",
                4: "3,4,3",
                5: "3,4,3,2",
                6: "3,4,3,3",
                7: "3,4,3,3,1",
                8: "3,4,3,3,2",
                9: "3,4,3,3,3,1",
                10: "4,4,3,3,3,2",
                11: "4,4,3,3,3,2,1",
                12: "4,4,3,3,3,2,1",
                13: "4,4,3,3,3,2,1,1",
                14: "4,4,3,3,3,2,1,1",
                15: "4,4,3,3,3,2,1,1,1",
                16: "4,4,3,3,3,2,1,1,1",
                17: "4,4,3,3,3,2,1,1,1,1",
                18: "4,4,3,3,3,3,1,1,1,1",
                19: "4,4,3,3,3,3,2,1,1,1",
                20: "4,4,3,3,3,3,2,2,1,1",
            },
            "subclass": [
                "Circle of the Arctic",
                "Circle of the Coast",
                "Circle of the Desert",
                "Circle of the Forest",
                "Circle of the Grassland",
                "Circle of the Moon",
                "Circle of the Mountain",
                "Circle of the Shepherd",
                "Circle of the Swamp",
                "Circle of the Underdark",
                "Circle of the Moon",
                "Circle of Dreams",
                "Circle of Spores",
                "Circle of Stars",
                "Circle of Wildfire",
            ],
            "tools": ["Herbalism Kit"],
            "weapons": [
                "Club",
                "Dagger",
                "Dart",
                "Javelin",
                "Mace",
                "Quarterstaff",
                "Scimitar",
                "Sickle",
                "Sling",
                "Spear",
            ],
        },
        "Fighter": {
            "armors": ["Light", "Medium", "Heavy", "Shield"],
            "features": {
                1: ["Fighting Style", "Second Wind"],
                2: ["Action Surge"],
                3: ["Martial Archetype"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack"],
                6: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                9: ["Indomitable"],
                11: ["Extra Attack"],
                12: ["Ability Score Improvement"],
                13: ["Indomitable"],
                14: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                17: ["Action Surge", "Indomitable"],
                19: ["Ability Score Improvement"],
                20: ["Extra Attack"],
            },
            "gold": "5d4",
            "hit_die": 10,
            "languages": [],
            "savingthrows": ["Constitution", "Strength"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Athletics",
                "History",
                "Insight",
                "Intimidation",
                "Perception",
                "Survival",
            ],
            "spells_known": {
                1: 0,
                2: 0,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 5,
                8: 6,
                9: 6,
                10: 7,
                11: 8,
                12: 8,
                13: 9,
                14: 10,
                15: 10,
                16: 11,
                17: 11,
                18: 11,
                19: 12,
                20: 13,
            },
            "spell_slots": {
                1: "0,0",
                2: "0,0",
                3: "2,2",
                4: "2,3",
                5: "2,3",
                6: "2,3",
                7: "2,4,2",
                8: "2,4,2",
                9: "2,4,2",
                10: "3,4,3",
                11: "3,4,3",
                12: "3,4,3",
                13: "3,4,3,2",
                14: "3,4,3,2",
                15: "3,4,3,2",
                16: "3,4,3,3",
                17: "3,4,3,3",
                18: "3,4,3,3",
                19: "3,4,3,3,1",
                20: "3,4,3,3,1",
            },
            "subclass": [
                "Arcane Archer",
                "Banneret",
                "Cavalier",
                "Champion",
                "Battle Master",
                "Eldritch Knight",
                "Psi Warrior",
                "Rune Knight",
                "Samurai",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Monk": {
            "armors": [],
            "features": {
                1: ["Martial Arts", "Unarmored Defense"],
                2: ["Ki", "Unarmored Movement"],
                3: ["Deflect Missiles", "Monastic Tradition"],
                4: ["Ability Score Improvement", "Slow Fall"],
                5: ["Extra Attack"],
                6: ["Ki-Empowered Strikes"],
                7: ["Evasion", "Stillness of Mind"],
                8: ["Ability Score Improvement"],
                10: ["Purity of Body"],
                12: ["Ability Score Improvement"],
                13: ["Tongue of the Sun and Moon"],
                14: ["Diamond Soul"],
                15: ["Timeless Body"],
                16: ["Ability Score Improvement"],
                17: ["Monastic Tradition"],
                18: ["Empty Body"],
                19: ["Ability Score Improvement"],
                20: ["Perfect Self"],
            },
            "gold": "5d4",
            "hit_die": 8,
            "languages": [],
            "savingthrows": ["Dexterity", "Strength"],
            "skills": [
                "Acrobatics",
                "Athletics",
                "History",
                "Insight",
                "Religion",
                "Stealth",
            ],
            "spell_slots": {},
            "subclass": [
                "Way of the Astral Self",
                "Way of the Drunken Master",
                "Way of the Four Elements",
                "Way of the Kensei",
                "Way of the Long Death",
                "Way of the Open Hand",
                "Way of Mercy",
                "Way of Shadow",
            ],
            "tools": [],
            "weapons": ["Simple", "Shortsword"],
        },
        "Paladin": {
            "armors": ["Light", "Medium", "Heavy", "Shield"],
            "features": {
                1: ["Divine Sense", "Lay on Hands"],
                2: ["Divine Smite", "Fighting Style", "Spellcasting"],
                3: ["Divine Health", "Sacred Oath"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack"],
                6: ["Aura of Protection"],
                8: ["Ability Score Improvement"],
                10: ["Aura of Courage"],
                11: ["Improved Divine Smite"],
                12: ["Ability Score Improvement"],
                14: ["Cleansing Touch"],
                16: ["Ability Score Improvement"],
                18: ["Aura of Courage", "Aura of Protection"],
                19: ["Ability Score Improvement"],
            },
            "gold": "5d4",
            "hit_die": 10,
            "languages": [],
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": [
                "Athletics",
                "Insight",
                "Intimidation",
                "Medicine",
                "Persuasion",
                "Religion",
            ],
            "spell_slots": {
                1: "0,0",
                2: "0,2",
                3: "0,3",
                4: "0,3",
                5: "0,4,2",
                6: "0,4,2",
                7: "0,4,3",
                8: "0,4,3",
                9: "0,4,3,2",
                10: "0,4,3,2",
                11: "0,4,3,3",
                12: "0,4,3,3",
                13: "0,4,3,3,1",
                14: "0,4,3,3,1",
                15: "0,4,3,3,2",
                16: "0,4,3,3,2",
                17: "0,4,3,3,3,1",
                18: "0,4,3,3,3,1",
                19: "0,4,3,3,3,2",
                20: "0,4,3,3,3,2",
            },
            "subclass": [
                "Oathbreaker",
                "Oath of Conquest",
                "Oath of Devotion",
                "Oath of Glory",
                "Oath of Redemption",
                "Oath of Vengeance",
                "Oath of the Ancients",
                "Oath of the Crown",
                "Oath of the Watchers",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Ranger": {
            "armors": ["Light", "Medium", "Shield"],
            "features": {
                1: ["Favored Enemy", "Natural Explorer"],
                2: ["Fighting Style", "Spellcasting"],
                3: ["Primeval Awareness", "Ranger Archetype"],
                4: ["Ability Score Improvement"],
                5: ["Extra Attack"],
                6: ["Favored Enemy", "Natural Explorer"],
                8: ["Ability Score Improvement", "Land's Stride"],
                10: ["Hide in Plain Sight", "Natural Explorer"],
                12: ["Ability Score Improvement"],
                14: ["Favored Enemy", "Vanish"],
                16: ["Ability Score Improvement"],
                18: ["Feral Senses"],
                19: ["Ability Score Improvement"],
                20: ["Foe Slayer"],
            },
            "gold": "5d4",
            "hit_die": 10,
            "languages": [],
            "savingthrows": ["Dexterity", "Strength"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Insight",
                "Investigation",
                "Nature",
                "Perception",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "spells_known": {
                1: 0,
                2: 2,
                3: 3,
                4: 3,
                5: 4,
                6: 4,
                7: 5,
                8: 5,
                9: 6,
                10: 6,
                11: 7,
                12: 7,
                13: 8,
                14: 8,
                15: 9,
                16: 9,
                17: 10,
                18: 10,
                19: 11,
                20: 11,
            },
            "spell_slots": {
                1: "0,0",
                2: "0,2",
                3: "0,3",
                4: "0,3",
                5: "0,4,2",
                6: "0,4,2",
                7: "0,4,3",
                8: "0,4,3",
                9: "0,4,3,2",
                10: "0,4,3,2",
                11: "0,4,3,3",
                12: "0,4,3,3",
                13: "0,4,3,3,1",
                14: "0,4,3,3,1",
                15: "0,4,3,3,2",
                16: "0,4,3,3,2",
                17: "0,4,3,3,3,1",
                18: "0,4,3,3,3,1",
                19: "0,4,3,3,3,2",
                20: "0,4,3,3,3,2",
            },
            "subclass": [
                "Beast Master",
                "Fey Wanderer",
                "Gloom Stalker",
                "Horizon Walker",
                "Hunter",
                "Monster Slayer",
                "Swarmkeeper",
            ],
            "tools": [],
            "weapons": ["Simple", "Martial"],
        },
        "Rogue": {
            "armors": ["Light"],
            "features": {
                1: ["Expertise", "Sneak Attack"],
                2: ["Cunning Action"],
                3: ["Roguish Archetype"],
                4: ["Ability Score Improvement"],
                5: ["Uncanny Dodge"],
                6: ["Expertise"],
                7: ["Evasion"],
                8: ["Ability Score Improvement"],
                10: ["Ability Score Improvement"],
                11: ["Reliable Talent"],
                12: ["Ability Score Improvement"],
                14: ["Blindsense"],
                15: ["Slippery Mind"],
                16: ["Ability Score Improvement"],
                18: ["Elusive"],
                19: ["Ability Score Improvement"],
                20: ["Stroke of Luck"],
            },
            "gold": "4d4",
            "hit_die": 8,
            "languages": ["Thieves' cant"],
            "savingthrows": ["Dexterity", "Intelligence"],
            "skills": [
                "Acrobatics",
                "Athletics",
                "Deception",
                "Insight",
                "Intimidation",
                "Investigation",
                "Perception",
                "Performance",
                "Persuasion",
                "Sleight of Hand",
                "Stealth",
            ],
            "spells_known": {
                1: 0,
                2: 0,
                3: 3,
                4: 4,
                5: 4,
                6: 4,
                7: 5,
                8: 6,
                9: 6,
                10: 7,
                11: 8,
                12: 8,
                13: 9,
                14: 10,
                15: 10,
                16: 11,
                17: 11,
                18: 11,
                19: 12,
                20: 13,
            },
            "spell_slots": {
                1: "0,0",
                2: "0,0",
                3: "2,2",
                4: "2,3",
                5: "2,3",
                6: "2,3",
                7: "2,4,2",
                8: "2,4,2",
                9: "2,4,2",
                10: "3,4,3",
                11: "3,4,3",
                12: "3,4,3",
                13: "3,4,3,2",
                14: "3,4,3,2",
                15: "3,4,3,2",
                16: "3,4,3,3",
                17: "3,4,3,3",
                18: "3,4,3,3",
                19: "3,4,3,3,1",
                20: "3,4,3,3,1",
            },
            "subclass": [
                "Arcane Trickster",
                "Assassin",
                "Inquisitive",
                "Mastermind",
                "Phantom",
                "Scout",
                "Soulknife",
                "Swashbuckler",
                "Thief",
            ],
            "tools": ["Thieves' tools"],
            "weapons": ["Simple", "Hand Crossbow", "Longsword", "Rapier", "Shortsword"],
        },
        "Sorcerer": {
            "armors": [],
            "features": {
                1: ["Sorcerous Origins", "Spellcasting"],
                2: ["Font of Magic"],
                3: ["Metamagic"],
                4: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                10: ["Metamagic"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                17: ["Metamagic"],
                19: ["Ability Score Improvement"],
                20: ["Sorcerous Restoration"],
            },
            "gold": "3d4",
            "hit_die": 6,
            "languages": [],
            "savingthrows": ["Charisma", "Constitution"],
            "skills": [
                "Arcana",
                "Deception",
                "Insight",
                "Intimidation",
                "Persuasion",
                "Religion",
            ],
            "spells_known": {
                1: 2,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 7,
                7: 8,
                8: 9,
                9: 10,
                10: 11,
                11: 12,
                12: 12,
                13: 13,
                14: 14,
                15: 14,
                16: 14,
                17: 15,
                18: 15,
                19: 15,
                20: 15,
            },
            "spell_slots": {
                1: "4,2",
                2: "4,3",
                3: "4,4,2",
                4: "5,4,3",
                5: "5,4,3,2",
                6: "5,4,3,3",
                7: "5,4,3,3,1",
                8: "5,4,3,3,2",
                9: "5,4,3,3,3,1",
                10: "6,4,3,3,3,2",
                11: "6,4,3,3,3,2,1",
                12: "6,4,3,3,3,2,1",
                13: "6,4,3,3,3,2,1,1",
                14: "6,4,3,3,3,2,1,1",
                15: "6,4,3,3,3,2,1,1,1",
                16: "6,4,3,3,3,2,1,1,1",
                17: "6,4,3,3,3,2,1,1,1,1",
                18: "6,4,3,3,3,3,1,1,1,1",
                19: "6,4,3,3,3,3,2,1,1,1",
                20: "6,4,3,3,3,3,2,2,1,1",
            },
            "subclass": [
                "Aberrant Mind",
                "Clockwork Soul",
                "Divine Soul",
                "Draconic Bloodline",
                "Shadow Magic",
                "Storm Sorcery",
                "Wild Magic",
            ],
            "tools": [],
            "weapons": ["Dagger", "Dart", "Light Crossbow", "Sling", "Quarterstaff"],
        },
        "Warlock": {
            "armors": ["Light"],
            "features": {
                1: ["Otherworldly Patron", "Pact Magic"],
                2: ["Eldritch Invocations"],
                3: ["Pact Boon"],
                4: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                11: ["Mystic Arcanum"],
                12: ["Ability Score Improvement"],
                13: ["Mystic Arcanum"],
                15: ["Mystic Arcanum"],
                16: ["Ability Score Improvement"],
                17: ["Mystic Arcanum"],
                19: ["Ability Score Improvement"],
                20: ["Eldritch Master"],
            },
            "gold": "4d4",
            "hit_die": 8,
            "languages": [],
            "savingthrows": ["Charisma", "Wisdom"],
            "skills": [
                "Arcana",
                "Deception",
                "History",
                "Intimidation",
                "Investigation",
                "Nature",
                "Religion",
            ],
            "spells_known": {
                1: 2,
                2: 3,
                3: 4,
                4: 5,
                5: 6,
                6: 7,
                7: 8,
                8: 9,
                9: 10,
                10: 10,
                11: 11,
                12: 11,
                13: 12,
                14: 12,
                15: 13,
                16: 13,
                17: 14,
                18: 14,
                19: 15,
                20: 15,
            },
            "spell_slots": {
                1: "2,1",
                2: "2,2",
                3: "2,2,2",
                4: "3,2,2",
                5: "3,2,2,2",
                6: "3,2,2,2",
                7: "3,2,2,2,2",
                8: "3,2,2,2,2",
                9: "3,2,2,2,2,2",
                10: "4,2,2,2,2,2",
                11: "4,3,3,3,3,3,1",
                12: "4,3,3,3,3,3,1",
                13: "4,3,3,3,3,3,1,1",
                14: "4,3,3,3,3,3,1,1",
                15: "4,3,3,3,3,3,1,1,1",
                16: "4,3,3,3,3,3,1,1,1",
                17: "4,4,4,4,4,4,1,1,1,1",
                18: "4,4,4,4,4,4,1,1,1,1",
                19: "4,4,4,4,4,4,1,1,1,1",
                20: "4,4,4,4,4,4,1,1,1,1",
            },
            "subclass": [
                "The Archfey",
                "The Celestial",
                "The Fathomless",
                "The Fiend",
                "The Genie",
                "The Great Old One",
                "The Hexblade",
                "The Undying",
            ],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Wizard": {
            "armors": [],
            "features": {
                1: ["Arcane Recovery", "Spellcasting"],
                2: ["Arcane Tradition"],
                4: ["Ability Score Improvement"],
                8: ["Ability Score Improvement"],
                12: ["Ability Score Improvement"],
                16: ["Ability Score Improvement"],
                18: ["Spell Mastery"],
                19: ["Ability Score Improvement"],
                20: ["Signature Spell"],
            },
            "gold": "4d4",
            "hit_die": 6,
            "languages": [],
            "savingthrows": ["Intelligence", "Wisdom"],
            "skills": [
                "Arcana",
                "History",
                "Insight",
                "Investigation",
                "Medicine",
                "Religion",
            ],
            "spell_slots": {
                1: "3,2",
                2: "3,3",
                3: "3,4,2",
                4: "4,4,3",
                5: "4,4,3,2",
                6: "4,4,3,3",
                7: "4,4,3,3,1",
                8: "4,4,3,3,2",
                9: "4,4,3,3,3,1",
                10: "5,4,3,3,3,2",
                11: "5,4,3,3,3,2,1",
                12: "5,4,3,3,3,2,1",
                13: "5,4,3,3,3,2,1,1",
                14: "5,4,3,3,3,2,1,1",
                15: "5,4,3,3,3,2,1,1,1",
                16: "5,4,3,3,3,2,1,1,1",
                17: "5,4,3,3,3,2,1,1,1,1",
                18: "5,4,3,3,3,3,1,1,1,1",
                19: "5,4,3,3,3,3,2,1,1,1",
                20: "5,4,3,3,3,3,2,2,1,1",
            },
            "subclass": [
                "Bladesinging",
                "Order of Scribes",
                "School of Abjuration",
                "School of Conjuration",
                "School of Divination",
                "School of Enchantment",
                "School of Evocation",
                "School of Illusion",
                "School of Necromancy",
                "School of Transmutation",
                "War Magic",
            ],
            "tools": [],
            "weapons": ["Dagger", "Dart", "Light Crossbow", "Sling", "Quarterstaff"],
        },
    },
}
