/*
Copyright © 2025 Marcus Taylor <mtaylor9754@hotmail.com>
*/
package d20

type Requirement struct {
	Ability string
	Score int
}

type Feat struct {
	Ability []Requirement
	Armors []string
	Category string
	Features []string
	Level int
	Tools []string
	Weapons []string
}

var characterFeats = map[string]Feat{
	"Ability Score Improvement": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Actor": {
		Ability: {{Ability: "Charisma", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Alert": {
		Ability: {},
		Armors: []string{},
		Category: "Origin",
		Features: []string{},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Archery": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Athlete": {
		Ability: {{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Blind Fighting": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Combat Prowess": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Dimensional Travel": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Energy Resistance": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Fate": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Fortitude": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Irresistible Offense": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Recovery": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Skill": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Speed": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Spell Recall": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{"Spellcasting"},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of the Night Spirit": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Boon of Truesight": {
		Ability: {},
		Armors: []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level: 19,
		Tools: []string{},
		Weapons: []string{},
	},
	"Charger": {
		Ability: {{Ability : "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Chef": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Crafter": {
		Ability: {},
		Armors: []string{},
		Category: "Origin",
		Features: []string{},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Crossbow Expert": {
		Ability: {{Ability: "Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Crusher": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Defense": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Defensive Duelist": {
		Ability: {{Ability: "Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Dual Wielder": {
		Ability: {{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Dueling": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Durable": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Elemental Adept": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{"Pact Magic", "Spellcasting"},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Fey-Touched": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Grappler": {
		"ability": {"Strength": 13, "Dexterity": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Great Weapon Fighting": {
		"ability": {},
		"armors": [],
		"category": "Fighting Style",
		"features": ["Fighting Style"],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Great Weapon Master": {
		"ability": {"Strength": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Healer": {
		"ability": {},
		"armors": [],
		"category": "Origin",
		"features": [],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Heavily Armored": {
		"ability": {},
		"armors": ["Medium"],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Heavy Armor Master": {
		"ability": {},
		"armors": ["Heavy"],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Inspiring Leader": {
		"ability": {"Wisdom": 13, "Charisma": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Interception": {
		"ability": {},
		"armors": [],
		"category": "Fighting Style",
		"features": ["Fighting Style"],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Keen Mind": {
		"ability": {"Intelligence": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Lightly Armored": {
		"ability": {},
		"armors": ["Light", "Shields"],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Lucky": {
		"ability": {},
		"armors": [],
		"category": "Origin",
		"features": [],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Mage Slayer": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Magic Initiate": {
		"ability": {},
		"armors": [],
		"category": "Origin",
		"features": [],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Martial Weapon Training": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Medium Armor Master": {
		"ability": {},
		"armors": ["Medium"],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Moderately Armored": {
		"ability": {},
		"armors": ["Light"],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Mounted Combatant": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Musician": {
		"ability": {},
		"armors": [],
		"category": "Origin",
		"features": [],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Observant": {
		"ability": {"Intelligence": 13, "Wisdom": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Piercer": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Poisoner": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Polearm Master": {
		"ability": {"Strength": 13, "Dexterity": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Protection": {
		"ability": {},
		"armors": [],
		"category": "Fighting Style",
		"features": ["Fighting Style"],
		"level": 1,
		"tools": [],
		"weapons": [],
	},
	"Resilient": {
		"ability": {},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Ritual Caster": {
		"ability": {"Intelligence": 13, "Wisdom": 13, "Charisma": 13},
		"armors": [],
		"category": "General",
		"features": [],
		"level": 4,
		"tools": [],
		"weapons": [],
	},
	"Savage Attacker": {
		Ability: {},
		Armors: []string{},
		Category: "Origin",
		Features: []string{},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Sentinel": {
		Ability: {{Ability: }"Strength", Score: 13}, {Ability: }"Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Shadow-Touched": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Sharpshooter": {
		Ability: {{Ability: }"Dexterity", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Shield Master": {
		Ability: {},
		Armors: []string{"Shield"},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Skilled": {
		Ability: {},
		Armors: []string{},
		Category: "Origin",
		Features: []string{},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Skill Expert": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Skulker": {
		Ability: {{Ability: }"Dexterity", Score: 13}},
		Armors: []string{},
		Features: []string{},
		Category: "General",
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Slasher": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Speedy": {
		Ability: {{Ability: }"Dexterity", Score: 13}, {Ability: }"Constitution", Score: 13}},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Spell Sniper": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{"Spellcasting", "Pact Magic"},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Tavern Brawler": {
		Ability: {},
		Armors: []string{},
		Category: "Origin",
		Features: []string{},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Telekinetic": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Telepathic": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Thrown Weapon Fighting": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Tough": {
		Ability: {},
		Armors: []string{},
		Features: []string{},
		Category: "Origin",
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Two-Weapon Fighting": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"Unarmed Fighting": {
		Ability: {},
		Armors: []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level: 1,
		Tools: []string{},
		Weapons: []string{},
	},
	"War Caster": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{"Spellcasting", "Pact Magic"},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
	"Weapon Master": {
		Ability: {},
		Armors: []string{},
		Category: "General",
		Features: []string{},
		Level: 4,
		Tools: []string{},
		Weapons: []string{},
	},
}
