/*
Copyright © 2025 Marcus Taylor <mtaylor9754@hotmail.com>
*/
package d20

type AbilityRequirement struct {
	Ability string
	Score   int
}

type Feat struct {
	Ability  []AbilityRequirement
	Armors   []string
	Category string
	Features []string
	Level    int
	Tools    []string
	Weapons  []string
}

var characterFeats = map[string]Feat{
	"Ability Score Improvement": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Actor": {
		Ability:  []AbilityRequirement{{Ability: "Charisma", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Alert": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Archery": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Athlete": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Blind Fighting": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Combat Prowess": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Dimensional Travel": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Energy Resistance": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Fate": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Fortitude": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Irresistible Offense": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Recovery": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Skill": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Speed": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Spell Recall": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{"Spellcasting"},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of the Night Spirit": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Boon of Truesight": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Epic Boon",
		Features: []string{},
		Level:    19,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Charger": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Chef": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Crafter": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Crossbow Expert": {
		Ability:  []AbilityRequirement{{Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Crusher": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Defense": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Defensive Duelist": {
		Ability:  []AbilityRequirement{{Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Dual Wielder": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Dueling": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Durable": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Elemental Adept": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{"Pact Magic", "Spellcasting"},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Fey-Touched": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Grappler": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Great Weapon Fighting": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Great Weapon Master": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Healer": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Heavily Armored": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Medium"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Heavy Armor Master": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Heavy"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Inspiring Leader": {
		Ability:  []AbilityRequirement{{Ability: "Wisdom", Score: 13}, {Ability: "Charisma", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Interception": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Keen Mind": {
		Ability:  []AbilityRequirement{{Ability: "Intelligence", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Lightly Armored": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Light", "Shields"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Lucky": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Mage Slayer": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Magic Initiate": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Martial Weapon Training": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Medium Armor Master": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Medium"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Moderately Armored": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Light"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Mounted Combatant": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Musician": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Observant": {
		Ability:  []AbilityRequirement{{Ability: "Intelligence", Score: 13}, {Ability: "Wisdom", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Piercer": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Poisoner": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Polearm Master": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Protection": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Resilient": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Ritual Caster": {
		Ability:  []AbilityRequirement{{Ability: "Intelligence", Score: 13}, {Ability: "Wisdom", Score: 13}, {Ability: "Charisma", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Savage Attacker": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Sentinel": {
		Ability:  []AbilityRequirement{{Ability: "Strength", Score: 13}, {Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Shadow-Touched": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Sharpshooter": {
		Ability:  []AbilityRequirement{{Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Shield Master": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{"Shield"},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Skilled": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Skill Expert": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Skulker": {
		Ability:  []AbilityRequirement{{Ability: "Dexterity", Score: 13}},
		Armors:   []string{},
		Features: []string{},
		Category: "General",
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Slasher": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Speedy": {
		Ability:  []AbilityRequirement{{Ability: "Dexterity", Score: 13}, {Ability: "Constitution", Score: 13}},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Spell Sniper": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{"Spellcasting", "Pact Magic"},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Tavern Brawler": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Origin",
		Features: []string{},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Telekinetic": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Telepathic": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Thrown Weapon Fighting": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Tough": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Features: []string{},
		Category: "Origin",
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Two-Weapon Fighting": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Unarmed Fighting": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "Fighting Style",
		Features: []string{"Fighting Style"},
		Level:    1,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"War Caster": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{"Spellcasting", "Pact Magic"},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
	"Weapon Master": {
		Ability:  []AbilityRequirement{},
		Armors:   []string{},
		Category: "General",
		Features: []string{},
		Level:    4,
		Tools:    []string{},
		Weapons:  []string{},
	},
}
