features = {
    "features": {
        "Aggressive": {},
        "Ambusher": {},
        "Amphibious": {},
        "Angelic Weapons": {},
        "Antimagic Susceptibility": {},
        "Avoidance": {},
        "Blind Senses": {},
        "Blood Frenzy": {},
        "Breath Weapon": {},
        "Brute": {},
        "Chameleon Skin": {},
        "Change Skin": {},
        "Change Shape": {},
        "Charge": {},
        "Charm": {},
        "Constrict": {},
        "Damage Absorbtion": {},
        "Damage Transfer": {},
        "Death Burst": {},
        "Devil Sight": {},
        "Dive": {},
        "Echolocation": {},
        "Elemental Body": {},
        "Enlarge": {},
        "Etherealness": {},
        "False Appearance": {},
        "Fey Ancestry": {},
        "Fiendish Blessing": {},
        "Flyby": {},
        "Frightful Presence": {},
        "Grappler": {},
        "Hold Breath": {},
        "Horrifying Visage": {},
        "Illumination": {},
        "Illusory Appearance": {},
        "Immutable Form": {},
        "Incorporeal Movement": {},
        "Innate Spellcasting": {},
        "Inscrutable": {},
        "Invisibility": {},
        "Keen Senses": {},
        "Labyrinthine Recall": {},
        "Leadership": {},
        "Legendary Resistance": {},
        "Life Drain": {},
        "Light Sensitivity": {},
        "Magic Resistance": {},
        "Magic Weapons": {},
        "Martial Advantage": {},
        "Mimicry": {},
        "Nimble Escape": {},
        "Otherworldly Perception": {},
        "Pack Tactics": {},
        "Parry": {},
        "Possession": {},
        "Pounce": {},
        "Psychic Defense": {},
        "Rampage": {},
        "Reactive": {},
        "Read Thoughts": {},
        "Reckless": {},
        "Redirect Attack": {},
        "Reel": {},
        "Regeneration": {},
        "Relentless": {},
        "Shadow Stealth": {},
        "Shapechanger": {},
        "Siege Monster": {},
        "Slippery": {},
        "Spellcasting": {},
        "Spider Climb": {},
        "Standing Leap": {},
        "Steadfast": {},
        "Stench": {},
        "Sunlight Sensitivity": {},
        "Superior Invisibility": {},
        "Sure-Footed": {},
        "Surprise Attack": {},
        "Swallow": {},
        "Teleport": {},
        "Terrain Camouflage": {},
        "Tunneler": {},
        "Turn Immunity": {},
        "Turn Resistance": {},
        "Two Heads": {},
        "Undead Fortitude": {},
        "Web": {},
        "Web Sense": {},
        "Web Walker": {},
        "Wounded Fury": {},
    },
}
