features = {
    "features": {
        "Aggressive": {},
        "Ambusher": {},
        "Amphibious": {},
        "Angelic Weapons": {},
        "Antimagic Susceptibility": {},
        "Avoidance": {},
        "Blind Senses": {},
        "Blood Frenzy": {},
        "Breath Weapon": {},
        "Brute": {},
        "Chameleon Skin": {},
        "Change Skin": {},
        "Change Shape": {},
        "Charge": {},
        "Charm": {},
        "Constrict": {},
        "Damage Absorbtion": {},
        "Damage Transfer": {},
        "Death Burst": {},
        "Devil Sight": {},
        "Dive": {},
        "Echolocation": {},
        "Elemental Body": {},
        "Enlarge": {},
        "Etherealness": {},
        "False Appearance": {},
        "Fey Ancestry": {},
        "Fiendish Blessing": {},
        "Flyby": {},
        "Frightful Presence": {},
        "Grappler": {},
        "Hold Breath": {},
        "Horrifying Visage": {},
        "Illumination": {},
        "Illusory Appearance": {},
        "Immutable Form": {},
        "Incorporeal Movement": {},
        "Innate Spellcasting": {},
        "Inscrutable": {},
        "Invisibility": {},
        "Keen Senses": {},
        "Labyrinthine Recall": {},
        "Leadership": {},
        "Legendary Resistance": {},
        "Life Drain": {},
    },
}
