languages = {
    "languages": [
        "Abyssal",
        "Celestial",
        "Common",
        "Deep Speech",
        "Draconic",
        "Dwarvish",
        "Elvish",
        "Giant",
        "Gith",
        "Gnomish",
        "Goblin",
        "Halfling",
        "Infernal",
        "Orc",
        "Primordial",
        "Sylvan",
        "Undercommon",
    ],
}
