lineages = {
    "lineages": {
        "Abyssal": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Poison Spray"], 3: ["Ray of Sickness"], 5: ["Hold Person"]},
            "tools": [],
            "traits": ["Infernal Legacy"],
            "weapons": [],
        },
        "Chthonic": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {
                1: ["Chill Touch"],
                3: ["False Life"],
                5: ["Ray of Enfeeblement"],
            },
            "tools": [],
            "traits": ["Legacy of Maladomini"],
            "weapons": [],
        },
        "Drow": {
            "armors": [],
            "bonus": {"Charisma": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Dancing Lights"], 3: ["Faerie Fire"], 5: ["Darkness"]},
            "tools": [],
            "traits": [
                "Drow Magic",
                "Drow Weapon Training",
                "Sunlight Sensitivity",
                "Superior Darkvision",
            ],
            "weapons": ["Hand Crossbow", "Rapier", "Shortsword"],
        },
        "Forest": {
            "armors": [],
            "bonus": {"Dexterity": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": ["Minor Illusion"],
            "tools": [],
            "traits": ["Natural Illusionist", "Speak with Small Beasts"],
            "weapons": [],
        },
        "High": {
            "armors": [],
            "bonus": {"Intelligence": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Prestidigitation"], 3: ["Detect Magic"], 5: ["Misty Step"]},
            "tools": [],
            "traits": ["Cantrip", "Elf Weapon Training", "Extra Language"],
            "weapons": ["Longsword", "Shortsword", "Shortbow", "Longbow"],
        },
        "Infernal": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": {1: ["Fire Bolt"], 3: ["Hellish Rebuke"], 5: ["Darkness"]},
            "tools": [],
            "traits": ["Legacy of Stygia"],
            "weapons": [],
        },
        "Rock": {
            "armors": [],
            "bonus": {"Constitution": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": ["Artisan's tools - Tinker's tools"],
            "traits": ["Artificer's Lore", "Tinker"],
            "weapons": [],
        },
        "Wood": {
            "armors": [],
            "bonus": {"Wisdom": 1},
            "languages": [],
            "resistances": [],
            "skills": [],
            "spells": [],
            "tools": [],
            "traits": ["Elf Weapon Training", "Fleet of Foot", "Mask of the Wild"],
            "weapons": ["Longsword", "Shortsword", "Shortbow", "Longbow"],
        },
    },
}
