multiclasses = {
    "multiclasses": {
        "Barbarian": {
            "requirements": {"Strength": 13},
            "armors": ["Shield"],
            "tools": [],
            "skills": [],
            "weapons": ["Martial"],
        },
        "Bard": {
            "requirements": {"Charisma": 13},
            "armors": ["Light"],
            "skills": [
                "Acrobatics",
                "Animal Handling",
                "Arcana",
                "Athletics",
                "Deception",
                "History",
                "Insight",
                "Intimidation",
                "Investigation",
                "Medicine",
                "Nature",
                "Perception",
                "Performance",
                "Persuasion",
                "Religion",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "tools": [
                "Musical Instrument - Bagpipes",
                "Musical Instrument - Birdpipes",
                "Musical Instrument - Drum",
                "Musical Instrument - Dulcimer",
                "Musical Instrument - Flute",
                "Musical Instrument - Glaur",
                "Musical Instrument - Hand Drum",
                "Musical Instrument - Longhorn",
                "Musical Instrument - Lute",
                "Musical Instrument - Lyre",
                "Musical Instrument - Horn",
                "Musical Instrument - Pan flute",
                "Musical Instrument - Shawm",
                "Musical Instrument - Songhorn",
                "Musical Instrument - Tantan",
                "Musical Instrument - Thelarr",
                "Musical Instrument - Tocken",
                "Musical Instrument - Viol",
                "Musical Instrument - Wargong",
                "Musical Instrument - Yarting",
                "Musical Instrument - Zulkoon",
            ],
            "weapons": [],
        },
        "Cleric": {
            "requirements": {"Wisdom": 13},
            "armors": ["Light", "Medium", "Shield"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Druid": {
            "requirements": {"Wisdom": 13},
            "armors": ["Light", "Shield"],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Fighter": {
            "requirements": {"Dexterity": 13, "Strength": 13},
            "armors": ["Light", "Medium", "Shield"],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        "Monk": {
            "requirements": {"Dexterity": 13, "Wisdom": 13},
            "armors": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Paladin": {
            "requirements": {"Strength": 13, "Charisma": 13},
            "armors": ["Light", "Medium", "Shield"],
            "skills": [],
            "tools": [],
            "weapons": ["Martial"],
        },
        "Ranger": {
            "requirements": {"Dexterity": 13, "Wisdom": 13},
            "armors": ["Light", "Medium", "Shield"],
            "skills": [
                "Animal Handling",
                "Athletics",
                "Insight",
                "Investigation",
                "Nature",
                "Perception",
                "Sleight of Hand",
                "Stealth",
                "Survival",
            ],
            "tools": [],
            "weapons": ["Martial"],
        },
        "Rogue": {
            "requirements": {"Dexterity": 13},
            "armors": ["Light"],
            "skills": [
                "Acrobatics",
                "Athletics",
                "Deception",
                "Insight",
                "Intimidation",
                "Investigation",
                "Perception",
                "Performance",
                "Persuasion",
                "Sleight of Hand",
                "Stealth",
            ],
            "tools": ["Thieves' Tools"],
            "weapons": [],
        },
        "Sorcerer": {
            "requirements": {"Charisma": 13},
            "armors": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
        "Warlock": {
            "requirements": {"Charisma": 13},
            "armors": ["Light"],
            "skills": [],
            "tools": [],
            "weapons": ["Simple"],
        },
        "Wizard": {
            "requirements": {"Intelligence": 13},
            "armors": [],
            "skills": [],
            "tools": [],
            "weapons": [],
        },
    },
}
