proficiencies = {
    "proficiencies": {
        "armors": [
            "Heavy",
            "Light",
            "Medium",
            "Shield",
        ],
        "tools": [
            "Artisan's Tools - Alchemists Supplies",
            "Artisan's Tools - Brewer's Supplies",
            "Artisan's Tools - Calligrapher's Supplies",
            "Artisan's Tools - Carpenter's Tools",
            "Artisan's Tools - Cartographer's Tools",
            "Artisan's Tools - Cobbler's Tools",
            "Artisan's Tools - Cook's utensils",
            "Artisan's Tools - Glassblower's Tools",
            "Artisan's Tools - Jeweler's Tools",
            "Artisan's Tools - Leatherworker's Tools",
            "Artisan's Tools - Mason's Tools",
            "Artisan's Tools - Painter's Supplies",
            "Artisan's Tools - Potter's Tools",
            "Artisan's Tools - Smith's Tools",
            "Artisan's Tools - Tinker's Tools",
            "Artisan's Tools - Weaver's Tools",
            "Artisan's Tools - Woodcarver's Tools",
            "Disguise kit",
            "Forgery kit",
            "Gaming set - Dice set",
            "Gaming set - Dragonchess set",
            "Gaming set - Playing card set",
            "Gaming set - Three-Dragon Ante set",
            "Herbalism kit",
            "Musical Instrument - Bagpipes",
            "Musical Instrument - Birdpipes",
            "Musical Instrument - Drum",
            "Musical Instrument - Dulcimer",
            "Musical Instrument - Flute",
            "Musical Instrument - Glaur",
            "Musical Instrument - Hand Drum",
            "Musical Instrument - Longhorn",
            "Musical Instrument - Lute",
            "Musical Instrument - Lyre",
            "Musical Instrument - Horn",
            "Musical Instrument - Pan flute",
            "Musical Instrument - Shawm",
            "Musical Instrument - Songhorn",
            "Musical Instrument - Tantan",
            "Musical Instrument - Thelarr",
            "Musical Instrument - Tocken",
            "Musical Instrument - Viol",
            "Musical Instrument - Wargong",
            "Musical Instrument - Yarting",
            "Musical Instrument - Zulkoon",
            "Navigator's Tools",
            "Poisoner's kit",
            "Thieves' Tools",
            "Vehicle",
        ],
        "weapons": {
            "Martial": [
                "Battleaxe",
                "Blowgun",
                "Flail",
                "Greataxe",
                "Greatsword",
                "Halberd",
                "Hand Crossbow",
                "Heavy Crossbow",
                "Lance",
                "Longbow",
                "Longsword",
                "Maul",
                "Morningstar",
                "Net",
                "Pike",
                "Rapier",
                "Scimitar",
                "Shortsword",
                "Trident",
                "War pick",
                "Warhammer",
                "Whip",
            ],
            "Simple": [
                "Club",
                "Dagger",
                "Dart",
                "Greatclub",
                "Handaxe",
                "Javelin",
                "Light Crossbow",
                "Light hammer",
                "Mace",
                "Quarterstaff",
                "Shortbow",
                "Sickle",
                "Sling",
                "Spear",
                "Unarmed strike",
            ],
        },
    },
}
