species = {
    "species": {
        "Aasimar": {
            "lineage": [],
            "resistances": ["Necrotic", "Radiant"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "traits": [
                "Celestial Resistance",
                "Celestial Revelation",
                "Darkvision",
                "Healing Hands",
                "Heavenly Wings",
                "Inner Radiance",
                "Light Bearer",
                "Necrotic Shroud",
            ],
        },
        "Dragonborn": {
            "lineage": [],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "traits": [
                "Breath Weapon",
                "Damage Resistance",
                "Darkvision",
                "Draconic Ancestry",
                "Draconic Flight",
            ],
        },
        "Dwarf": {
            "lineage": [],
            "resistances": ["Poison"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "traits": [
                "Darkvision",
                "Dwarven Resilience",
                "Dwarven Toughness",
                "Stonecunning",
            ],
        },
        "Elf": {
            "lineage": ["Drow", "High", "Wood"],
            "resistances": ["Charm", "Sleep"],
            "size": "Medium",
            "skills": ["Perception"],
            "spells": [],
            "traits": [
                "Darkvision",
                "Elf Lineage",
                "Fey Ancestry",
                "Keen Senses",
                "Trance",
            ],
        },
        "Gnome": {
            "lineage": ["Deep", "Forest", "Rock"],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "traits": ["Darkvision", "Gnome Cunning", "Gnomish Lineage"],
        },
        "Goliath": {
            "lineage": [],
            "resistances": [],
            "size": "Medium",
            "skills": ["Athletics"],
            "spells": [],
            "traits": [
                "Giant Ancestry",
                "Large Form",
                "Powerful Build",
            ],
        },
        "Halfling": {
            "lineage": [],
            "resistances": [],
            "size": "Small",
            "skills": [],
            "spells": [],
            "traits": ["Brave", "Halfling Nimbleness", "Luck", "Naturally Stealthy"],
        },
        "Human": {
            "lineage": [],
            "resistances": [],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "traits": ["Resourceful", "Skillful", "Versatile"],
        },
        "Orc": {
            "lineage": [],
            "resistances": [],
            "size": "Medium",
            "skills": ["Intimidation"],
            "spells": [],
            "traits": ["Adrenaline Rush", "Darkvision", "Relentless Endurance"],
        },
        "Tiefling": {
            "lineage": [
                "Abyssal",
                "Chthonic",
                "Internal",
            ],
            "resistances": ["Fire"],
            "size": "Medium",
            "skills": [],
            "spells": [],
            "traits": ["Darkvision", "Fiendish Legacy", "Otherworldly Presence"],
        },
    },
}
